"""HR service layer public API.

This module exposes all HR services and their associated types.
"""
from app.services.hr.errors import (
    # Base errors (re-exported for convenience)
    ServiceError,
    NotFoundError,
    ValidationError,
    ConflictError,
    ForbiddenError,
    # Employee errors
    EmployeeNotFoundError,
    EmployeeAlreadyExistsError,
    EmployeeStatusError,
    InvalidManagerError,
    # Organization errors
    DepartmentNotFoundError,
    DesignationNotFoundError,
    HDTeamNotFoundError,
    CircularDepartmentError,
    # Leave errors
    LeaveTypeNotFoundError,
    LeavePolicyNotFoundError,
    LeaveAllocationNotFoundError,
    LeaveApplicationNotFoundError,
    InsufficientLeaveBalanceError,
    LeaveOverlapError,
    LeaveStatusTransitionError,
    LeavePolicyViolationError,
    HolidayListNotFoundError,
    # Attendance errors
    ShiftTypeNotFoundError,
    ShiftAssignmentNotFoundError,
    ShiftAssignmentError,
    AttendanceNotFoundError,
    DuplicateAttendanceError,
    CheckInError,
    CheckOutError,
    AttendanceRequestNotFoundError,
    AttendanceRequestStatusError,
    # Payroll errors
    SalaryComponentNotFoundError,
    SalarySlipNotFoundError,
    PayrollEntryNotFoundError,
    SalaryStructureNotFoundError,
    SalaryStructureAssignmentNotFoundError,
    NoSalaryAssignmentError,
    PayrollAlreadyProcessedError,
    SlipStatusTransitionError,
    # Recruitment errors
    JobOpeningNotFoundError,
    ApplicantNotFoundError,
    JobOfferNotFoundError,
    InterviewNotFoundError,
    ApplicantPipelineError,
    OfferExpiredError,
    # Training errors
    TrainingProgramNotFoundError,
    TrainingEventNotFoundError,
    TrainingRegistrationError,
    TrainingResultNotFoundError,
    TrainingEventStatusError,
    # Appraisal errors
    AppraisalNotFoundError,
    AppraisalTemplateNotFoundError,
    AppraisalStatusTransitionError,
    AppraisalStatusError,
    # Lifecycle errors
    OnboardingNotFoundError,
    SeparationNotFoundError,
    PromotionNotFoundError,
    TransferNotFoundError,
    LifecycleStatusError,
)

from app.services.hr.organization import OrganizationService
from app.services.hr.organization_types import (
    DepartmentFilters,
    DepartmentCreateData,
    DepartmentUpdateData,
    DepartmentNode,
    DepartmentHeadcount,
    DesignationFilters,
    DesignationCreateData,
    DesignationUpdateData,
    HDTeamFilters,
    HDTeamCreateData,
    HDTeamUpdateData,
    TeamMemberData,
)

from app.services.hr.employees import EmployeeService
from app.services.hr.employee_types import (
    EmployeeFilters,
    EmployeeCreateData,
    EmployeeUpdateData,
    EmployeeSummary,
    OrgChartNode,
    TerminationData,
    BulkResult,
)

from app.services.hr.leave import LeaveService
from app.services.hr.leave_types import (
    LeaveTypeCreateData,
    LeaveTypeUpdateData,
    LeavePolicyCreateData,
    LeavePolicyUpdateData,
    LeavePolicyDetailData,
    AllocationFilters,
    AllocationCreateData,
    AllocationUpdateData,
    BulkAllocationData,
    BulkAllocationResult,
    ApplicationFilters,
    ApplicationCreateData,
    ApplicationUpdateData,
    BulkApprovalResult,
    LeaveBalanceInfo,
    ValidationResult,
    OverlapInfo,
    HolidayListCreateData,
    HolidayListUpdateData,
    HolidayData,
)

from app.services.hr.attendance import AttendanceService
from app.services.hr.attendance_types import (
    ShiftTypeCreateData,
    ShiftTypeUpdateData,
    ShiftAssignmentFilters,
    ShiftAssignmentCreateData,
    ShiftAssignmentUpdateData,
    BulkShiftAssignmentData,
    AttendanceFilters,
    AttendanceCreateData,
    AttendanceUpdateData,
    CheckInData,
    CheckOutData,
    AttendanceRequestFilters,
    AttendanceRequestCreateData,
    AttendanceSummary,
    DepartmentAttendanceSummary,
    WorkingHoursSummary,
    LateArrivalRecord,
)

from app.services.hr.payroll import PayrollService
from app.services.hr.payroll_types import (
    SalaryComponentCreateData,
    SalaryComponentUpdateData,
    SalaryStructureFilters,
    SalaryStructureCreateData,
    SalaryStructureUpdateData,
    StructureEarningData,
    StructureDeductionData,
    StructureAssignmentFilters,
    StructureAssignmentCreateData,
    StructureAssignmentUpdateData,
    PayrollEntryFilters,
    PayrollEntryCreateData,
    PayrollEntryUpdateData,
    SalarySlipFilters,
    SalarySlipCreateData,
    SalarySlipUpdateData,
    SlipEarningData,
    SlipDeductionData,
    SlipPaymentData,
    SlipGenerationResult,
    SlipCalculation,
    ComponentAmount,
    YTDEarnings,
    PayrollSummary,
    BulkSlipResult,
)

from app.services.hr.compliance import (
    ComplianceService,
    ComplianceModule,
    ComplianceModuleBase,
    ComplianceResult,
    ComplianceSchedule,
    DeductionConfig,
    DeductionResult,
    DeductionTotals,
    DeductionType,
    EmployeeDeductionConfig,
    EmployeeInfo,
    PayrollComplianceSummary,
    SalaryInput,
)
from app.services.hr.compliance.ng import NigerianComplianceModule

from app.services.hr.recruitment import RecruitmentService
from app.services.hr.recruitment_types import (
    JobOpeningFilters,
    JobOpeningCreateData,
    JobOpeningUpdateData,
    ApplicantFilters,
    ApplicantCreateData,
    ApplicantUpdateData,
    ApplicantPipelineMove,
    InterviewFilters,
    InterviewScheduleData,
    InterviewUpdateData,
    InterviewFeedbackData,
    JobOfferFilters,
    JobOfferCreateData,
    JobOfferUpdateData,
    OfferTermData,
    HiringData,
    RecruitmentMetrics,
    PipelineSummary,
)

from app.services.hr.training import TrainingService
from app.services.hr.training_types import (
    TrainingProgramFilters,
    TrainingProgramCreateData,
    TrainingProgramUpdateData,
    TrainingEventFilters,
    TrainingEventCreateData,
    TrainingEventUpdateData,
    EventEmployeeData,
    TrainingResultFilters,
    TrainingResultCreateData,
    TrainingResultUpdateData,
    BulkRegistrationData,
    BulkRegistrationResult,
    TrainingMetrics,
    EmployeeTrainingHistory,
)

from app.services.hr.appraisal import AppraisalService
from app.services.hr.appraisal_types import (
    TemplateFilters,
    TemplateCreateData,
    TemplateUpdateData,
    TemplateGoalData,
    AppraisalFilters,
    AppraisalCreateData,
    AppraisalUpdateData,
    AppraisalGoalData,
    AppraisalScoreData,
    AppraisalMetrics,
    EmployeeAppraisalSummary,
    TeamAppraisalSummary,
)

from app.services.hr.lifecycle import LifecycleService
from app.services.hr.lifecycle_types import (
    OnboardingFilters,
    OnboardingCreateData,
    OnboardingUpdateData,
    OnboardingActivityData,
    SeparationFilters,
    SeparationCreateData,
    SeparationUpdateData,
    SeparationActivityData,
    PromotionFilters,
    PromotionCreateData,
    PromotionUpdateData,
    PromotionDetailData,
    TransferFilters,
    TransferCreateData,
    TransferUpdateData,
    TransferDetailData,
    LifecycleMetrics,
    EmployeeLifecycleHistory,
)

from app.services.hr.settings import HRSettingsService
from app.services.hr.settings_types import (
    HRSettingsData,
    HRSettingsUpdateData,
    LeaveEncashmentPolicyData,
    LeaveEncashmentPolicyUpdateData,
    HolidayCalendarFilters,
    HolidayCalendarCreateData,
    HolidayCalendarUpdateData,
    HolidayData as SettingsHolidayData,
    SalaryBandFilters,
    SalaryBandCreateData,
    SalaryBandUpdateData,
    ChecklistTemplateFilters,
    ChecklistTemplateCreateData,
    ChecklistTemplateUpdateData,
    DeductionConfigFilters,
    DeductionConfigCreateData,
    DeductionConfigUpdateData,
)

__all__ = [
    # Services
    "OrganizationService",
    "EmployeeService",
    "LeaveService",
    "AttendanceService",
    "PayrollService",
    "ComplianceService",
    "NigerianComplianceModule",
    "RecruitmentService",
    "TrainingService",
    "AppraisalService",
    "LifecycleService",
    "HRSettingsService",
    # Errors
    "ServiceError",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "ForbiddenError",
    "EmployeeNotFoundError",
    "EmployeeAlreadyExistsError",
    "EmployeeStatusError",
    "InvalidManagerError",
    "DepartmentNotFoundError",
    "DesignationNotFoundError",
    "HDTeamNotFoundError",
    "CircularDepartmentError",
    "LeaveTypeNotFoundError",
    "LeavePolicyNotFoundError",
    "LeaveAllocationNotFoundError",
    "LeaveApplicationNotFoundError",
    "InsufficientLeaveBalanceError",
    "LeaveOverlapError",
    "LeaveStatusTransitionError",
    "LeavePolicyViolationError",
    "HolidayListNotFoundError",
    "ShiftTypeNotFoundError",
    "ShiftAssignmentNotFoundError",
    "ShiftAssignmentError",
    "AttendanceNotFoundError",
    "DuplicateAttendanceError",
    "CheckInError",
    "CheckOutError",
    "AttendanceRequestNotFoundError",
    "AttendanceRequestStatusError",
    "SalaryComponentNotFoundError",
    "SalarySlipNotFoundError",
    "PayrollEntryNotFoundError",
    "SalaryStructureNotFoundError",
    "SalaryStructureAssignmentNotFoundError",
    "NoSalaryAssignmentError",
    "PayrollAlreadyProcessedError",
    "SlipStatusTransitionError",
    # Recruitment errors
    "JobOpeningNotFoundError",
    "ApplicantNotFoundError",
    "JobOfferNotFoundError",
    "InterviewNotFoundError",
    "ApplicantPipelineError",
    "OfferExpiredError",
    # Training errors
    "TrainingProgramNotFoundError",
    "TrainingEventNotFoundError",
    "TrainingRegistrationError",
    "TrainingResultNotFoundError",
    "TrainingEventStatusError",
    # Appraisal errors
    "AppraisalNotFoundError",
    "AppraisalTemplateNotFoundError",
    "AppraisalStatusTransitionError",
    "AppraisalStatusError",
    # Lifecycle errors
    "OnboardingNotFoundError",
    "SeparationNotFoundError",
    "PromotionNotFoundError",
    "TransferNotFoundError",
    "LifecycleStatusError",
    # Organization types
    "DepartmentFilters",
    "DepartmentCreateData",
    "DepartmentUpdateData",
    "DepartmentNode",
    "DepartmentHeadcount",
    "DesignationFilters",
    "DesignationCreateData",
    "DesignationUpdateData",
    "HDTeamFilters",
    "HDTeamCreateData",
    "HDTeamUpdateData",
    "TeamMemberData",
    # Employee types
    "EmployeeFilters",
    "EmployeeCreateData",
    "EmployeeUpdateData",
    "EmployeeSummary",
    "OrgChartNode",
    "TerminationData",
    "BulkResult",
    # Leave types
    "LeaveTypeCreateData",
    "LeaveTypeUpdateData",
    "LeavePolicyCreateData",
    "LeavePolicyUpdateData",
    "LeavePolicyDetailData",
    "AllocationFilters",
    "AllocationCreateData",
    "AllocationUpdateData",
    "BulkAllocationData",
    "BulkAllocationResult",
    "ApplicationFilters",
    "ApplicationCreateData",
    "ApplicationUpdateData",
    "BulkApprovalResult",
    "LeaveBalanceInfo",
    "ValidationResult",
    "OverlapInfo",
    "HolidayListCreateData",
    "HolidayListUpdateData",
    "HolidayData",
    # Attendance types
    "ShiftTypeCreateData",
    "ShiftTypeUpdateData",
    "ShiftAssignmentFilters",
    "ShiftAssignmentCreateData",
    "ShiftAssignmentUpdateData",
    "BulkShiftAssignmentData",
    "AttendanceFilters",
    "AttendanceCreateData",
    "AttendanceUpdateData",
    "CheckInData",
    "CheckOutData",
    "AttendanceRequestFilters",
    "AttendanceRequestCreateData",
    "AttendanceSummary",
    "DepartmentAttendanceSummary",
    "WorkingHoursSummary",
    "LateArrivalRecord",
    # Payroll types
    "SalaryComponentCreateData",
    "SalaryComponentUpdateData",
    "SalaryStructureFilters",
    "SalaryStructureCreateData",
    "SalaryStructureUpdateData",
    "StructureEarningData",
    "StructureDeductionData",
    "StructureAssignmentFilters",
    "StructureAssignmentCreateData",
    "StructureAssignmentUpdateData",
    "PayrollEntryFilters",
    "PayrollEntryCreateData",
    "PayrollEntryUpdateData",
    "SalarySlipFilters",
    "SalarySlipCreateData",
    "SalarySlipUpdateData",
    "SlipEarningData",
    "SlipDeductionData",
    "SlipPaymentData",
    "SlipGenerationResult",
    "SlipCalculation",
    "ComponentAmount",
    "YTDEarnings",
    "PayrollSummary",
    "BulkSlipResult",
    # Compliance types
    "ComplianceModule",
    "ComplianceModuleBase",
    "ComplianceResult",
    "ComplianceSchedule",
    "DeductionConfig",
    "DeductionResult",
    "DeductionTotals",
    "DeductionType",
    "EmployeeDeductionConfig",
    "EmployeeInfo",
    "PayrollComplianceSummary",
    "SalaryInput",
    # Recruitment types
    "JobOpeningFilters",
    "JobOpeningCreateData",
    "JobOpeningUpdateData",
    "ApplicantFilters",
    "ApplicantCreateData",
    "ApplicantUpdateData",
    "ApplicantPipelineMove",
    "InterviewFilters",
    "InterviewScheduleData",
    "InterviewUpdateData",
    "InterviewFeedbackData",
    "JobOfferFilters",
    "JobOfferCreateData",
    "JobOfferUpdateData",
    "OfferTermData",
    "HiringData",
    "RecruitmentMetrics",
    "PipelineSummary",
    # Training types
    "TrainingProgramFilters",
    "TrainingProgramCreateData",
    "TrainingProgramUpdateData",
    "TrainingEventFilters",
    "TrainingEventCreateData",
    "TrainingEventUpdateData",
    "EventEmployeeData",
    "TrainingResultFilters",
    "TrainingResultCreateData",
    "TrainingResultUpdateData",
    "BulkRegistrationData",
    "BulkRegistrationResult",
    "TrainingMetrics",
    "EmployeeTrainingHistory",
    # Appraisal types
    "TemplateFilters",
    "TemplateCreateData",
    "TemplateUpdateData",
    "TemplateGoalData",
    "AppraisalFilters",
    "AppraisalCreateData",
    "AppraisalUpdateData",
    "AppraisalGoalData",
    "AppraisalScoreData",
    "AppraisalMetrics",
    "EmployeeAppraisalSummary",
    "TeamAppraisalSummary",
    # Lifecycle types
    "OnboardingFilters",
    "OnboardingCreateData",
    "OnboardingUpdateData",
    "OnboardingActivityData",
    "SeparationFilters",
    "SeparationCreateData",
    "SeparationUpdateData",
    "SeparationActivityData",
    "PromotionFilters",
    "PromotionCreateData",
    "PromotionUpdateData",
    "PromotionDetailData",
    "TransferFilters",
    "TransferCreateData",
    "TransferUpdateData",
    "TransferDetailData",
    "LifecycleMetrics",
    "EmployeeLifecycleHistory",
    # Settings types
    "HRSettingsData",
    "HRSettingsUpdateData",
    "LeaveEncashmentPolicyData",
    "LeaveEncashmentPolicyUpdateData",
    "HolidayCalendarFilters",
    "HolidayCalendarCreateData",
    "HolidayCalendarUpdateData",
    "SettingsHolidayData",
    "SalaryBandFilters",
    "SalaryBandCreateData",
    "SalaryBandUpdateData",
    "ChecklistTemplateFilters",
    "ChecklistTemplateCreateData",
    "ChecklistTemplateUpdateData",
    "DeductionConfigFilters",
    "DeductionConfigCreateData",
    "DeductionConfigUpdateData",
]
