"""add_employee_hr_relationships

Revision ID: 13f8158555e9
Revises: 0b207e32b691
Create Date: 2025-12-09 10:21:43.395597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f8158555e9'
down_revision: Union[str, None] = '0b207e32b691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('designation_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('reports_to_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employees_reports_to_id'), 'employees', ['reports_to_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'designations', ['designation_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'employees', ['reports_to_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.add_column('sales_persons', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_persons_employee_id'), 'sales_persons', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'sales_persons', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_persons', type_='foreignkey')
    op.drop_index(op.f('ix_sales_persons_employee_id'), table_name='sales_persons')
    op.drop_column('sales_persons', 'employee_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_reports_to_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_column('employees', 'reports_to_id')
    op.drop_column('employees', 'designation_id')
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
