"""add_customer_splynx_fields

Revision ID: 1fc71201f7cd
Revises: db48b78d6c98
Create Date: 2025-12-09 06:47:13.417858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc71201f7cd'
down_revision: Union[str, None] = 'db48b78d6c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('zoho_id', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('address_2', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('gps', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('billing_type', sa.Enum('PREPAID', 'PREPAID_MONTHLY', 'RECURRING', name='billingtype'), nullable=True))
    op.add_column('customers', sa.Column('base_station', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('building_type', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('vat_id', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('mrr', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('customers', sa.Column('daily_prepaid_cost', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('customers', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('conversion_date', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('last_online', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('added_by', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('added_by_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('referrer', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('labels', sa.Text(), nullable=True))
    op.create_index(op.f('ix_customers_base_station'), 'customers', ['base_station'], unique=False)
    op.create_index(op.f('ix_customers_partner_id'), 'customers', ['partner_id'], unique=False)
    op.create_index(op.f('ix_customers_zoho_id'), 'customers', ['zoho_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_zoho_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_partner_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_base_station'), table_name='customers')
    op.drop_column('customers', 'labels')
    op.drop_column('customers', 'referrer')
    op.drop_column('customers', 'added_by_id')
    op.drop_column('customers', 'added_by')
    op.drop_column('customers', 'last_online')
    op.drop_column('customers', 'conversion_date')
    op.drop_column('customers', 'partner_id')
    op.drop_column('customers', 'daily_prepaid_cost')
    op.drop_column('customers', 'mrr')
    op.drop_column('customers', 'vat_id')
    op.drop_column('customers', 'building_type')
    op.drop_column('customers', 'base_station')
    op.drop_column('customers', 'billing_type')
    op.drop_column('customers', 'gps')
    op.drop_column('customers', 'zip_code')
    op.drop_column('customers', 'address_2')
    op.drop_column('customers', 'billing_email')
    op.drop_column('customers', 'zoho_id')
    # ### end Alembic commands ###
