"""Add NAS fields to routers table

Revision ID: 2dd07b89432d
Revises: 9babb511d5d2
Create Date: 2025-12-09 08:00:53.151811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd07b89432d'
down_revision: Union[str, None] = '9babb511d5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routers', sa.Column('radius_secret', sa.String(length=255), nullable=True))
    op.add_column('routers', sa.Column('radius_coa_port', sa.Integer(), nullable=True))
    op.add_column('routers', sa.Column('radius_accounting_interval', sa.Integer(), nullable=True))
    op.add_column('routers', sa.Column('api_login', sa.String(length=100), nullable=True))
    op.add_column('routers', sa.Column('api_password', sa.String(length=255), nullable=True))
    op.add_column('routers', sa.Column('api_port', sa.Integer(), nullable=True))
    op.add_column('routers', sa.Column('ssh_port', sa.Integer(), nullable=True))
    op.add_column('routers', sa.Column('pool_ids', sa.Text(), nullable=True))
    op.add_column('routers', sa.Column('partners_ids', sa.Text(), nullable=True))
    op.add_column('routers', sa.Column('additional_attributes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_routers_ip'), 'routers', ['ip'], unique=False)
    op.create_index(op.f('ix_routers_location_id'), 'routers', ['location_id'], unique=False)
    op.create_index(op.f('ix_routers_nas_ip'), 'routers', ['nas_ip'], unique=False)
    op.create_index(op.f('ix_routers_nas_type'), 'routers', ['nas_type'], unique=False)
    op.create_index(op.f('ix_routers_status'), 'routers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routers_status'), table_name='routers')
    op.drop_index(op.f('ix_routers_nas_type'), table_name='routers')
    op.drop_index(op.f('ix_routers_nas_ip'), table_name='routers')
    op.drop_index(op.f('ix_routers_location_id'), table_name='routers')
    op.drop_index(op.f('ix_routers_ip'), table_name='routers')
    op.drop_column('routers', 'additional_attributes')
    op.drop_column('routers', 'partners_ids')
    op.drop_column('routers', 'pool_ids')
    op.drop_column('routers', 'ssh_port')
    op.drop_column('routers', 'api_port')
    op.drop_column('routers', 'api_password')
    op.drop_column('routers', 'api_login')
    op.drop_column('routers', 'radius_accounting_interval')
    op.drop_column('routers', 'radius_coa_port')
    op.drop_column('routers', 'radius_secret')
    # ### end Alembic commands ###
