"""add_erpnext_accounting_models

Revision ID: 3df42795f1ea
Revises: 4a47c51b1fa1
Create Date: 2025-12-09 09:53:49.732650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df42795f1ea'
down_revision: Union[str, None] = '4a47c51b1fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
