"""Add IPv6Network table

Revision ID: 4a47c51b1fa1
Revises: 89bca93902fc
Create Date: 2025-12-09 09:25:26.729011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a47c51b1fa1'
down_revision: Union[str, None] = '89bca93902fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
