"""Add ticket_messages and transaction_categories tables

Revision ID: 6c2d531e250d
Revises: 06601d712f57
Create Date: 2025-12-09 07:51:25.085227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c2d531e250d'
down_revision: Union[str, None] = '06601d712f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'is_group',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accounts', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bank_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('bank_accounts', 'is_company_account',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bank_accounts', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bank_accounts', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bank_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SETTLED', 'UNRECONCILED', 'RECONCILED', 'CANCELLED', name='banktransactionstatus'),
               nullable=False)
    op.alter_column('bank_transactions', 'deposit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('bank_transactions', 'withdrawal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('bank_transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('bank_transactions', 'allocated_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('bank_transactions', 'unallocated_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('bank_transactions', 'docstatus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bank_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('OPEN', 'PENDING', 'RESOLVED', 'SNOOZED', name='conversationstatus'),
               nullable=False)
    op.alter_column('conversations', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='conversationpriority'),
               nullable=False)
    op.alter_column('conversations', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('credit_notes', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('credit_notes', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ISSUED', 'APPLIED', 'CANCELLED', name='creditnotestatus'),
               nullable=False)
    op.alter_column('credit_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('credit_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customers', 'customer_type',
               existing_type=postgresql.ENUM('RESIDENTIAL', 'BUSINESS', 'ENTERPRISE', name='customertype'),
               nullable=False)
    op.alter_column('customers', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CANCELLED', 'PROSPECT', name='customerstatus'),
               nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('employees', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE', name='employmentstatus'),
               nullable=False)
    op.alter_column('employees', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'APPROVED', 'PAID', 'CANCELLED', name='expensestatus'),
               nullable=False)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('gl_entries', 'debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('gl_entries', 'credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('gl_entries', 'debit_in_account_currency',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('gl_entries', 'credit_in_account_currency',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('gl_entries', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('gl_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('journal_entries', 'voucher_type',
               existing_type=postgresql.ENUM('JOURNAL_ENTRY', 'BANK_ENTRY', 'CASH_ENTRY', 'CREDIT_CARD_ENTRY', 'DEBIT_NOTE', 'CREDIT_NOTE', 'CONTRA_ENTRY', 'EXCISE_ENTRY', 'WRITE_OFF_ENTRY', 'OPENING_ENTRY', 'DEPRECIATION_ENTRY', 'EXCHANGE_RATE_REVALUATION', name='journalentrytype'),
               nullable=False)
    op.alter_column('journal_entries', 'total_debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('journal_entries', 'total_credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('journal_entries', 'is_opening',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('journal_entries', 'docstatus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('messages', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('network_monitors', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('network_monitors', 'send_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('network_monitors', 'access_device',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('network_monitors', 'is_ping',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('network_monitors', 'ping_state',
               existing_type=postgresql.ENUM('UP', 'DOWN', 'UNKNOWN', name='monitorstate'),
               nullable=False)
    op.alter_column('network_monitors', 'snmp_state',
               existing_type=postgresql.ENUM('UP', 'DOWN', 'UNKNOWN', name='monitorstate'),
               nullable=False)
    op.alter_column('network_monitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('network_monitors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('CASH', 'BANK_TRANSFER', 'CARD', 'MOBILE_MONEY', 'PAYSTACK', 'FLUTTERWAVE', 'OTHER', name='paymentmethod'),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pops', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('pops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('OPEN', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='projectstatus'),
               nullable=False)
    op.alter_column('projects', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='projectpriority'),
               nullable=False)
    op.alter_column('projects', 'percent_complete',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('projects', 'estimated_costing',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'total_costing_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'total_expense_claim',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'total_sales_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'total_billable_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'total_billed_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'gross_margin',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('purchase_invoices', 'grand_total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('purchase_invoices', 'outstanding_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('purchase_invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('purchase_invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('purchase_invoices', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PAID', 'UNPAID', 'OVERDUE', 'CANCELLED', 'RETURN', name='purchaseinvoicestatus'),
               nullable=False)
    op.alter_column('purchase_invoices', 'docstatus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('purchase_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('routers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('routers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('subscriptions', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('splynx_tariff_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('service_type', sa.Enum('INTERNET', 'VOICE', 'CUSTOM', 'BUNDLE', name='subscriptiontype'), nullable=False))
    op.add_column('subscriptions', sa.Column('ipv4_address', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('ipv6_address', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('mac_address', sa.String(length=50), nullable=True))
    op.add_column('subscriptions', sa.Column('router_id', sa.Integer(), nullable=True))
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'CANCELLED', 'PENDING', name='subscriptionstatus'),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_ipv4_address'), 'subscriptions', ['ipv4_address'], unique=False)
    op.create_index(op.f('ix_subscriptions_router_id'), 'subscriptions', ['router_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_service_type'), 'subscriptions', ['service_type'], unique=False)
    op.create_index(op.f('ix_subscriptions_splynx_tariff_id'), 'subscriptions', ['splynx_tariff_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tariff_id'), 'subscriptions', ['tariff_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'tariffs', ['tariff_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'routers', ['router_id'], ['id'])
    op.alter_column('sync_logs', 'sync_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sync_logs', 'status',
               existing_type=postgresql.ENUM('STARTED', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus'),
               nullable=False)
    op.alter_column('sync_logs', 'records_fetched',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sync_logs', 'records_created',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sync_logs', 'records_updated',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sync_logs', 'records_failed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sync_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tariffs', 'tariff_type',
               existing_type=postgresql.ENUM('INTERNET', 'RECURRING', 'ONE_TIME', name='tarifftype'),
               nullable=False)
    op.alter_column('tariffs', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('tariffs', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('tariffs', 'vat_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('tariffs', 'with_vat',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tariffs', 'available_for_services',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tariffs', 'show_on_customer_portal',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tariffs', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tariffs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tariffs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tickets', 'source',
               existing_type=postgresql.ENUM('ERPNEXT', 'SPLYNX', 'CHATWOOT', name='ticketsource'),
               nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('OPEN', 'REPLIED', 'RESOLVED', 'CLOSED', name='ticketstatus'),
               nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'),
               nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('OPEN', 'REPLIED', 'RESOLVED', 'CLOSED', name='ticketstatus'),
               nullable=True)
    op.alter_column('tickets', 'source',
               existing_type=postgresql.ENUM('ERPNEXT', 'SPLYNX', 'CHATWOOT', name='ticketsource'),
               nullable=True)
    op.alter_column('tariffs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tariffs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tariffs', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tariffs', 'show_on_customer_portal',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tariffs', 'available_for_services',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tariffs', 'with_vat',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tariffs', 'vat_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('tariffs', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('tariffs', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('tariffs', 'tariff_type',
               existing_type=postgresql.ENUM('INTERNET', 'RECURRING', 'ONE_TIME', name='tarifftype'),
               nullable=True)
    op.alter_column('sync_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sync_logs', 'records_failed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_logs', 'records_updated',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_logs', 'records_created',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_logs', 'records_fetched',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sync_logs', 'status',
               existing_type=postgresql.ENUM('STARTED', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus'),
               nullable=True)
    op.alter_column('sync_logs', 'sync_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_tariff_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_splynx_tariff_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_service_type'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_router_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_ipv4_address'), table_name='subscriptions')
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUSPENDED', 'CANCELLED', 'PENDING', name='subscriptionstatus'),
               nullable=True)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('subscriptions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('subscriptions', 'router_id')
    op.drop_column('subscriptions', 'mac_address')
    op.drop_column('subscriptions', 'ipv6_address')
    op.drop_column('subscriptions', 'ipv4_address')
    op.drop_column('subscriptions', 'service_type')
    op.drop_column('subscriptions', 'splynx_tariff_id')
    op.drop_column('subscriptions', 'tariff_id')
    op.alter_column('routers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('routers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('purchase_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('purchase_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('purchase_invoices', 'docstatus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_invoices', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PAID', 'UNPAID', 'OVERDUE', 'CANCELLED', 'RETURN', name='purchaseinvoicestatus'),
               nullable=True)
    op.alter_column('purchase_invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('purchase_invoices', 'paid_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('purchase_invoices', 'outstanding_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('purchase_invoices', 'grand_total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'gross_margin',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'total_billed_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'total_billable_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'total_sales_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'total_expense_claim',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'total_costing_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'estimated_costing',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('projects', 'is_active',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('projects', 'percent_complete',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('projects', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='projectpriority'),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('OPEN', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='projectstatus'),
               nullable=True)
    op.alter_column('pops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pops', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('CASH', 'BANK_TRANSFER', 'CARD', 'MOBILE_MONEY', 'PAYSTACK', 'FLUTTERWAVE', 'OTHER', name='paymentmethod'),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('network_monitors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('network_monitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('network_monitors', 'snmp_state',
               existing_type=postgresql.ENUM('UP', 'DOWN', 'UNKNOWN', name='monitorstate'),
               nullable=True)
    op.alter_column('network_monitors', 'ping_state',
               existing_type=postgresql.ENUM('UP', 'DOWN', 'UNKNOWN', name='monitorstate'),
               nullable=True)
    op.alter_column('network_monitors', 'is_ping',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('network_monitors', 'access_device',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('network_monitors', 'send_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('network_monitors', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('journal_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('journal_entries', 'docstatus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('journal_entries', 'is_opening',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('journal_entries', 'total_credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('journal_entries', 'total_debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('journal_entries', 'voucher_type',
               existing_type=postgresql.ENUM('JOURNAL_ENTRY', 'BANK_ENTRY', 'CASH_ENTRY', 'CREDIT_CARD_ENTRY', 'DEBIT_NOTE', 'CREDIT_NOTE', 'CONTRA_ENTRY', 'EXCISE_ENTRY', 'WRITE_OFF_ENTRY', 'OPENING_ENTRY', 'DEPRECIATION_ENTRY', 'EXCHANGE_RATE_REVALUATION', name='journalentrytype'),
               nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'PAID', 'PARTIALLY_PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'),
               nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('gl_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('gl_entries', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('gl_entries', 'credit_in_account_currency',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('gl_entries', 'debit_in_account_currency',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('gl_entries', 'credit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('gl_entries', 'debit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('expenses', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'APPROVED', 'PAID', 'CANCELLED', name='expensestatus'),
               nullable=True)
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('employees', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('employees', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE', name='employmentstatus'),
               nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customers', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CANCELLED', 'PROSPECT', name='customerstatus'),
               nullable=True)
    op.alter_column('customers', 'customer_type',
               existing_type=postgresql.ENUM('RESIDENTIAL', 'BUSINESS', 'ENTERPRISE', name='customertype'),
               nullable=True)
    op.alter_column('credit_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('credit_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('credit_notes', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ISSUED', 'APPLIED', 'CANCELLED', name='creditnotestatus'),
               nullable=True)
    op.alter_column('credit_notes', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conversations', 'message_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conversations', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='conversationpriority'),
               nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=postgresql.ENUM('OPEN', 'PENDING', 'RESOLVED', 'SNOOZED', name='conversationstatus'),
               nullable=True)
    op.alter_column('bank_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bank_transactions', 'docstatus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bank_transactions', 'unallocated_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('bank_transactions', 'allocated_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('bank_transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('bank_transactions', 'withdrawal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('bank_transactions', 'deposit',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('bank_transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SETTLED', 'UNRECONCILED', 'RECONCILED', 'CANCELLED', name='banktransactionstatus'),
               nullable=True)
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bank_accounts', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bank_accounts', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bank_accounts', 'is_company_account',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bank_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('accounts', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accounts', 'is_group',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
