"""Add IPv4Network and PaymentMethod tables

Revision ID: 89bca93902fc
Revises: cfa110cc819b
Create Date: 2025-12-09 09:18:51.144248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bca93902fc'
down_revision: Union[str, None] = 'cfa110cc819b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
