"""add_splynx_payment_type_to_payments

Revision ID: 9389be4f5ff6
Revises: a1b2c3d4e5f6
Create Date: 2025-12-12 15:10:54.211797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9389be4f5ff6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('purchase_invoice_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('splynx_payment_type', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_purchase_invoice_id'), 'payments', ['purchase_invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_splynx_payment_type'), 'payments', ['splynx_payment_type'], unique=False)
    op.create_index(op.f('ix_payments_supplier_id'), 'payments', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'purchase_invoices', ['purchase_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_supplier_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_splynx_payment_type'), table_name='payments')
    op.drop_index(op.f('ix_payments_purchase_invoice_id'), table_name='payments')
    op.drop_column('payments', 'splynx_payment_type')
    op.drop_column('payments', 'purchase_invoice_id')
    op.drop_column('payments', 'supplier_id')
    # ### end Alembic commands ###
