"""add_tariffs_and_routers_tables

Revision ID: 989aa0032afc
Revises: 506ac98642d2
Create Date: 2025-12-09 06:35:39.597327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989aa0032afc'
down_revision: Union[str, None] = '506ac98642d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
