"""Add full fields to Project and Expense models with FK relationships

Revision ID: 9babb511d5d2
Revises: 6c2d531e250d
Create Date: 2025-12-09 07:56:52.812897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9babb511d5d2'
down_revision: Union[str, None] = '6c2d531e250d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Expenses table - nullable columns first
    op.add_column('expenses', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('employee_name', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('erpnext_employee', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('erpnext_project', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('remark', sa.Text(), nullable=True))

    # Decimal columns with server_default for existing rows
    op.add_column('expenses', sa.Column('total_claimed_amount', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('expenses', sa.Column('total_sanctioned_amount', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('expenses', sa.Column('total_amount_reimbursed', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('expenses', sa.Column('total_advance_amount', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('expenses', sa.Column('total_taxes_and_charges', sa.Numeric(), nullable=False, server_default='0'))

    op.add_column('expenses', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('payable_account', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('mode_of_payment', sa.String(length=100), nullable=True))
    op.add_column('expenses', sa.Column('clearance_date', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('approval_status', sa.String(length=50), nullable=True))
    op.add_column('expenses', sa.Column('expense_approver', sa.String(length=255), nullable=True))

    # Boolean and integer with server_default
    op.add_column('expenses', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('expenses', sa.Column('docstatus', sa.Integer(), nullable=False, server_default='0'))

    op.add_column('expenses', sa.Column('task', sa.String(length=255), nullable=True))
    op.alter_column('expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_expenses_approval_status'), 'expenses', ['approval_status'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_posting_date'), 'expenses', ['posting_date'], unique=False)
    op.create_index(op.f('ix_expenses_project_id'), 'expenses', ['project_id'], unique=False)
    op.create_foreign_key('fk_expenses_project_id', 'expenses', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('fk_expenses_employee_id', 'expenses', 'employees', ['employee_id'], ['id'])
    op.drop_column('expenses', 'vendor')

    # Projects table - nullable columns
    op.add_column('projects', sa.Column('project_type', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('cost_center', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('project_manager_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('erpnext_customer', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('erpnext_sales_order', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('percent_complete_method', sa.String(length=100), nullable=True))

    # Decimal columns with server_default for existing rows
    op.add_column('projects', sa.Column('actual_time', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('total_consumed_material_cost', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('total_purchase_cost', sa.Numeric(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('per_gross_margin', sa.Numeric(), nullable=False, server_default='0'))

    # Boolean with server_default
    op.add_column('projects', sa.Column('collect_progress', sa.Boolean(), nullable=False, server_default='false'))

    op.add_column('projects', sa.Column('frequency', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('from_time', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('to_time', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('message', sa.Text(), nullable=True))
    op.alter_column('projects', 'erpnext_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_projects_project_manager_id'), 'projects', ['project_manager_id'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_foreign_key('fk_projects_project_manager_id', 'projects', 'employees', ['project_manager_id'], ['id'])
    op.create_foreign_key('fk_projects_customer_id', 'projects', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_customer_id', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_project_manager_id', 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.alter_column('projects', 'erpnext_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('projects', 'message')
    op.drop_column('projects', 'to_time')
    op.drop_column('projects', 'from_time')
    op.drop_column('projects', 'frequency')
    op.drop_column('projects', 'collect_progress')
    op.drop_column('projects', 'per_gross_margin')
    op.drop_column('projects', 'total_purchase_cost')
    op.drop_column('projects', 'total_consumed_material_cost')
    op.drop_column('projects', 'actual_time')
    op.drop_column('projects', 'percent_complete_method')
    op.drop_column('projects', 'erpnext_sales_order')
    op.drop_column('projects', 'erpnext_customer')
    op.drop_column('projects', 'project_manager_id')
    op.drop_column('projects', 'customer_id')
    op.drop_column('projects', 'cost_center')
    op.drop_column('projects', 'project_type')
    op.add_column('expenses', sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('fk_expenses_employee_id', 'expenses', type_='foreignkey')
    op.drop_constraint('fk_expenses_project_id', 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_project_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_posting_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_approval_status'), table_name='expenses')
    op.alter_column('expenses', 'expense_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('expenses', 'task')
    op.drop_column('expenses', 'docstatus')
    op.drop_column('expenses', 'is_paid')
    op.drop_column('expenses', 'expense_approver')
    op.drop_column('expenses', 'approval_status')
    op.drop_column('expenses', 'clearance_date')
    op.drop_column('expenses', 'mode_of_payment')
    op.drop_column('expenses', 'payable_account')
    op.drop_column('expenses', 'company')
    op.drop_column('expenses', 'total_taxes_and_charges')
    op.drop_column('expenses', 'total_advance_amount')
    op.drop_column('expenses', 'total_amount_reimbursed')
    op.drop_column('expenses', 'total_sanctioned_amount')
    op.drop_column('expenses', 'total_claimed_amount')
    op.drop_column('expenses', 'remark')
    op.drop_column('expenses', 'erpnext_project')
    op.drop_column('expenses', 'project_id')
    op.drop_column('expenses', 'erpnext_employee')
    op.drop_column('expenses', 'employee_name')
    op.drop_column('expenses', 'employee_id')
    # ### end Alembic commands ###
