"""Add employee_id FK to conversations

Revision ID: b477cc6d91d3
Revises: 13f8158555e9
Create Date: 2025-12-09 10:26:13.453205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b477cc6d91d3'
down_revision: Union[str, None] = '13f8158555e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_employee_id'), 'conversations', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_employee_id'), table_name='conversations')
    op.drop_column('conversations', 'employee_id')
    # ### end Alembic commands ###
