"""Update Ticket model with project FK and full HD Ticket fields

Revision ID: cfa110cc819b
Revises: 2dd07b89432d
Create Date: 2025-12-09 08:34:20.183357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa110cc819b'
down_revision: Union[str, None] = '2dd07b89432d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('erpnext_customer', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('erpnext_project', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('ticket_type', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('assigned_employee_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('resolution_team', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('response_by', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('resolution_by', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('agreement_status', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('first_responded_on', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('resolution', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('resolution_details', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('feedback_rating', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('feedback_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tickets_assigned_employee_id'), 'tickets', ['assigned_employee_id'], unique=False)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_type'), 'tickets', ['ticket_type'], unique=False)
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'employees', ['assigned_employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_ticket_type'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_employee_id'), table_name='tickets')
    op.drop_column('tickets', 'feedback_text')
    op.drop_column('tickets', 'feedback_rating')
    op.drop_column('tickets', 'resolution_details')
    op.drop_column('tickets', 'resolution')
    op.drop_column('tickets', 'first_responded_on')
    op.drop_column('tickets', 'agreement_status')
    op.drop_column('tickets', 'resolution_by')
    op.drop_column('tickets', 'response_by')
    op.drop_column('tickets', 'resolution_team')
    op.drop_column('tickets', 'assigned_employee_id')
    op.drop_column('tickets', 'ticket_type')
    op.drop_column('tickets', 'erpnext_project')
    op.drop_column('tickets', 'erpnext_customer')
    op.drop_column('tickets', 'project_id')
    # ### end Alembic commands ###
