"""fix_tariff_unique_constraint

Revision ID: db48b78d6c98
Revises: 989aa0032afc
Create Date: 2025-12-09 06:40:19.411632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db48b78d6c98'
down_revision: Union[str, None] = '989aa0032afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariffs_splynx_id'), table_name='tariffs')
    op.create_index(op.f('ix_tariffs_splynx_id'), 'tariffs', ['splynx_id'], unique=False)
    op.create_unique_constraint('uq_tariff_splynx_id_type', 'tariffs', ['splynx_id', 'tariff_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tariff_splynx_id_type', 'tariffs', type_='unique')
    op.drop_index(op.f('ix_tariffs_splynx_id'), table_name='tariffs')
    op.create_index(op.f('ix_tariffs_splynx_id'), 'tariffs', ['splynx_id'], unique=True)
    # ### end Alembic commands ###
