"""Accounting entity definitions: accounts, bank, fiscal, cost centers."""
from .base import FieldType, EntityConfig

ACCOUNTING_ENTITIES: dict[str, EntityConfig] = {
    "accounts": {
        "model_name": "Account",
        "display_name": "Chart of Accounts",
        "description": "GL accounts",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "account_number": {"type": FieldType.STRING, "unique": True, "max_length": 50, "description": "Account number"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Account name"},
            "account_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["asset", "liability", "equity", "income", "expense"], "description": "Account type"},
            "parent_account": {"type": FieldType.STRING, "description": "Parent account number"},
            "is_group": {"type": FieldType.BOOLEAN, "default": False, "description": "Is group account"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
        },
        "required_fields": ["name", "account_type"],
        "unique_fields": ["account_number"],
        "lookup_fields": ["id", "account_number", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "bank_accounts": {
        "model_name": "BankAccount",
        "display_name": "Bank Accounts",
        "description": "Company bank accounts",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "account_name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Account name"},
            "bank": {"type": FieldType.STRING, "max_length": 255, "description": "Bank name"},
            "bank_account_no": {"type": FieldType.STRING, "max_length": 100, "description": "Bank account number"},
            "account": {"type": FieldType.STRING, "max_length": 255, "description": "GL account link"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "currency": {"type": FieldType.STRING, "max_length": 10, "default": "NGN", "description": "Currency"},
            "is_company_account": {"type": FieldType.BOOLEAN, "default": True, "description": "Is company account"},
            "is_default": {"type": FieldType.BOOLEAN, "default": False, "description": "Is default account"},
            "disabled": {"type": FieldType.BOOLEAN, "default": False, "description": "Is disabled"},
        },
        "required_fields": ["account_name"],
        "unique_fields": ["bank_account_no"],
        "lookup_fields": ["id", "account_name", "bank_account_no"],
        "dependencies": ["accounts"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "bank_transactions": {
        "model_name": "BankTransaction",
        "display_name": "Bank Transactions",
        "description": "Bank statement transactions",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "date": {"type": FieldType.DATETIME, "required": True, "description": "Transaction date"},
            "bank_account_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "bank_accounts", "fk_lookup_fields": ["id", "account_name"], "description": "Bank account"},
            "deposit": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Deposit amount"},
            "withdrawal": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Withdrawal amount"},
            "currency": {"type": FieldType.STRING, "max_length": 10, "default": "NGN", "description": "Currency"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "reference_number": {"type": FieldType.STRING, "max_length": 255, "description": "Reference number"},
            "transaction_id": {"type": FieldType.STRING, "max_length": 255, "description": "External transaction ID"},
            "transaction_type": {"type": FieldType.STRING, "max_length": 100, "description": "Transaction type"},
            "payee_name": {"type": FieldType.STRING, "max_length": 255, "normalizer": "name", "description": "Payee name"},
            "payee_account": {"type": FieldType.STRING, "max_length": 100, "description": "Payee account"},
            "status": {"type": FieldType.ENUM, "enum_values": ["pending", "settled", "unreconciled", "reconciled", "cancelled"], "default": "pending", "description": "Status"},
            "party_type": {"type": FieldType.STRING, "max_length": 100, "description": "Party type (Customer/Supplier)"},
            "party": {"type": FieldType.STRING, "max_length": 255, "description": "Party name"},
        },
        "required_fields": ["date"],
        "unique_fields": ["transaction_id"],
        "lookup_fields": ["id", "transaction_id", "reference_number"],
        "dependencies": ["bank_accounts"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "journal_entries": {
        "model_name": "JournalEntry",
        "display_name": "Journal Entries",
        "description": "General journal entries",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "voucher_type": {"type": FieldType.ENUM, "enum_values": ["journal_entry", "bank_entry", "cash_entry", "credit_card_entry", "debit_note", "credit_note", "contra_entry", "write_off_entry", "opening_entry", "depreciation_entry"], "default": "journal_entry", "description": "Voucher type"},
            "posting_date": {"type": FieldType.DATETIME, "required": True, "description": "Posting date"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "total_debit": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total debit"},
            "total_credit": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total credit"},
            "cheque_no": {"type": FieldType.STRING, "max_length": 100, "description": "Cheque number"},
            "cheque_date": {"type": FieldType.DATETIME, "description": "Cheque date"},
            "user_remark": {"type": FieldType.STRING, "description": "Remarks/memo"},
            "is_opening": {"type": FieldType.BOOLEAN, "default": False, "description": "Is opening entry"},
        },
        "required_fields": ["posting_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["accounts"],
        "supports_upsert": False,  # JEs should not be updated, only created
        "supports_rollback": True,
    },

    "cost_centers": {
        "model_name": "CostCenter",
        "display_name": "Cost Centers",
        "description": "Departmental cost centers",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "cost_center_name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Cost center name"},
            "cost_center_number": {"type": FieldType.STRING, "max_length": 50, "description": "Cost center number"},
            "parent_cost_center": {"type": FieldType.STRING, "max_length": 255, "description": "Parent cost center"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "is_group": {"type": FieldType.BOOLEAN, "default": False, "description": "Is group"},
            "disabled": {"type": FieldType.BOOLEAN, "default": False, "description": "Is disabled"},
        },
        "required_fields": ["cost_center_name"],
        "unique_fields": ["cost_center_number"],
        "lookup_fields": ["id", "cost_center_name", "cost_center_number"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "fiscal_years": {
        "model_name": "FiscalYear",
        "display_name": "Fiscal Years",
        "description": "Accounting fiscal years",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "year": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 20, "description": "Year name (e.g., 2024)"},
            "year_start_date": {"type": FieldType.DATE, "required": True, "description": "Year start date"},
            "year_end_date": {"type": FieldType.DATE, "required": True, "description": "Year end date"},
            "is_short_year": {"type": FieldType.BOOLEAN, "default": False, "description": "Is short year"},
            "disabled": {"type": FieldType.BOOLEAN, "default": False, "description": "Is disabled"},
        },
        "required_fields": ["year", "year_start_date", "year_end_date"],
        "unique_fields": ["year"],
        "lookup_fields": ["id", "year"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "fiscal_periods": {
        "model_name": "FiscalPeriod",
        "display_name": "Fiscal Periods",
        "description": "Monthly/quarterly accounting periods",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "fiscal_year_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "fiscal_years", "fk_lookup_fields": ["id", "year"], "description": "Fiscal year"},
            "period_name": {"type": FieldType.STRING, "required": True, "max_length": 50, "description": "Period name (e.g., 2024-01)"},
            "period_type": {"type": FieldType.ENUM, "enum_values": ["month", "quarter", "year"], "default": "month", "description": "Period type"},
            "start_date": {"type": FieldType.DATE, "required": True, "description": "Period start date"},
            "end_date": {"type": FieldType.DATE, "required": True, "description": "Period end date"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "soft_closed", "hard_closed"], "default": "open", "description": "Period status"},
        },
        "required_fields": ["fiscal_year_id", "period_name", "start_date", "end_date"],
        "unique_fields": [],
        "lookup_fields": ["id", "period_name"],
        "dependencies": ["fiscal_years"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "modes_of_payment": {
        "model_name": "ModeOfPayment",
        "display_name": "Payment Modes",
        "description": "Payment methods (cash, bank, etc.)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "mode_of_payment": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Payment mode name"},
            "type": {"type": FieldType.ENUM, "enum_values": ["cash", "bank", "general"], "default": "general", "description": "Payment type"},
            "enabled": {"type": FieldType.BOOLEAN, "default": True, "description": "Is enabled"},
        },
        "required_fields": ["mode_of_payment"],
        "unique_fields": ["mode_of_payment"],
        "lookup_fields": ["id", "mode_of_payment"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "supplier_groups": {
        "model_name": "SupplierGroup",
        "display_name": "Supplier Groups",
        "description": "Vendor/supplier categories",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Group name"},
            "parent_supplier_group": {"type": FieldType.STRING, "max_length": 255, "description": "Parent group name"},
            "is_group": {"type": FieldType.BOOLEAN, "default": False, "description": "Is group"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "gl_entries": {
        "model_name": "GLEntry",
        "display_name": "GL Entries",
        "description": "General ledger entries (read-only import)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "posting_date": {"type": FieldType.DATETIME, "required": True, "description": "Posting date"},
            "account": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "GL account"},
            "debit": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Debit amount"},
            "credit": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Credit amount"},
            "party_type": {"type": FieldType.STRING, "max_length": 100, "description": "Party type"},
            "party": {"type": FieldType.STRING, "max_length": 255, "description": "Party name"},
            "voucher_type": {"type": FieldType.STRING, "max_length": 100, "description": "Voucher type"},
            "voucher_no": {"type": FieldType.STRING, "max_length": 100, "description": "Voucher number"},
            "cost_center": {"type": FieldType.STRING, "max_length": 255, "description": "Cost center"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "fiscal_year": {"type": FieldType.STRING, "max_length": 20, "description": "Fiscal year"},
        },
        "required_fields": ["posting_date", "account"],
        "unique_fields": [],
        "lookup_fields": ["id", "voucher_no"],
        "dependencies": ["accounts"],
        "supports_upsert": False,
        "supports_rollback": False,  # GL entries are immutable
    },

    "exchange_rates": {
        "model_name": "ExchangeRate",
        "display_name": "Exchange Rates",
        "description": "Currency exchange rates",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "from_currency": {"type": FieldType.STRING, "required": True, "max_length": 3, "description": "From currency (e.g., USD)"},
            "to_currency": {"type": FieldType.STRING, "required": True, "max_length": 3, "description": "To currency (e.g., NGN)"},
            "rate_date": {"type": FieldType.DATE, "required": True, "description": "Rate date"},
            "rate": {"type": FieldType.DECIMAL, "required": True, "description": "Exchange rate"},
            "source": {"type": FieldType.ENUM, "enum_values": ["manual", "api", "import"], "default": "import", "description": "Rate source"},
        },
        "required_fields": ["from_currency", "to_currency", "rate_date", "rate"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "payment_allocations": {
        "model_name": "PaymentAllocation",
        "display_name": "Payment Allocations",
        "description": "Payment to invoice allocation links",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "payment_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "payments", "fk_lookup_fields": ["id", "receipt_number"], "description": "Payment"},
            "invoice_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "invoices", "fk_lookup_fields": ["id", "invoice_number"], "description": "Invoice"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Allocated amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "allocation_date": {"type": FieldType.DATE, "description": "Allocation date"},
        },
        "required_fields": ["payment_id", "invoice_id", "amount"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["payments", "invoices"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "payment_methods": {
        "model_name": "PaymentMethod",
        "display_name": "Payment Methods",
        "description": "Customer payment methods (cards, bank accounts)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "method_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["card", "bank_account", "mobile_money"], "description": "Method type"},
            "is_default": {"type": FieldType.BOOLEAN, "default": False, "description": "Is default method"},
            "last_four": {"type": FieldType.STRING, "max_length": 4, "description": "Last 4 digits"},
            "card_brand": {"type": FieldType.STRING, "max_length": 50, "description": "Card brand"},
            "bank_name": {"type": FieldType.STRING, "max_length": 255, "description": "Bank name"},
            "expiry_month": {"type": FieldType.INTEGER, "description": "Card expiry month"},
            "expiry_year": {"type": FieldType.INTEGER, "description": "Card expiry year"},
            "status": {"type": FieldType.ENUM, "enum_values": ["active", "expired", "disabled"], "default": "active", "description": "Status"},
        },
        "required_fields": ["customer_id", "method_type"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["customers"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
