"""Asset entity definitions: assets, asset categories."""
from .base import FieldType, EntityConfig

ASSET_ENTITIES: dict[str, EntityConfig] = {
    "asset_categories": {
        "model_name": "AssetCategory",
        "display_name": "Asset Categories",
        "description": "Fixed asset categories with depreciation settings",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "asset_category_name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Category name"},
            "enable_cwip_accounting": {"type": FieldType.BOOLEAN, "default": False, "description": "Enable CWIP accounting"},
            "depreciation_method": {"type": FieldType.ENUM, "enum_values": ["straight_line", "double_declining_balance", "written_down_value", "manual"], "default": "straight_line", "description": "Depreciation method"},
            "total_number_of_depreciations": {"type": FieldType.INTEGER, "description": "Total number of depreciations"},
            "frequency_of_depreciation": {"type": FieldType.INTEGER, "description": "Frequency (months)"},
            "depreciation_account": {"type": FieldType.STRING, "max_length": 255, "description": "Depreciation expense account"},
            "accumulated_depreciation_account": {"type": FieldType.STRING, "max_length": 255, "description": "Accumulated depreciation account"},
        },
        "required_fields": ["asset_category_name"],
        "unique_fields": ["asset_category_name"],
        "lookup_fields": ["id", "asset_category_name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "assets": {
        "model_name": "Asset",
        "display_name": "Fixed Assets",
        "description": "Fixed asset register",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "asset_name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Asset name"},
            "asset_category": {"type": FieldType.STRING, "max_length": 255, "description": "Asset category"},
            "asset_category_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "asset_categories", "fk_lookup_fields": ["id", "asset_category_name"], "description": "Asset category reference"},
            "item_code": {"type": FieldType.STRING, "max_length": 255, "description": "Item code"},
            "item_name": {"type": FieldType.STRING, "max_length": 255, "description": "Item name"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "location": {"type": FieldType.STRING, "max_length": 255, "description": "Location"},
            "custodian_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Custodian"},
            "department": {"type": FieldType.STRING, "max_length": 255, "description": "Department"},
            "cost_center": {"type": FieldType.STRING, "max_length": 255, "description": "Cost center"},
            "purchase_date": {"type": FieldType.DATE, "description": "Purchase date"},
            "available_for_use_date": {"type": FieldType.DATE, "description": "Available for use date"},
            "gross_purchase_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Gross purchase amount"},
            "purchase_receipt": {"type": FieldType.STRING, "max_length": 255, "description": "Purchase receipt"},
            "purchase_invoice": {"type": FieldType.STRING, "max_length": 255, "description": "Purchase invoice"},
            "supplier": {"type": FieldType.STRING, "max_length": 255, "description": "Supplier name"},
            "supplier_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "suppliers", "fk_lookup_fields": ["id", "email", "name"], "description": "Supplier reference"},
            "asset_quantity": {"type": FieldType.INTEGER, "default": 1, "description": "Quantity"},
            "opening_accumulated_depreciation": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Opening accumulated depreciation"},
            "asset_value": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Current book value"},
            "expected_value_after_useful_life": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Salvage value"},
            "calculate_depreciation": {"type": FieldType.BOOLEAN, "default": True, "description": "Calculate depreciation"},
            "is_existing_asset": {"type": FieldType.BOOLEAN, "default": False, "description": "Is existing asset"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "partially_depreciated", "fully_depreciated", "sold", "scrapped", "in_maintenance", "out_of_order"], "default": "draft", "description": "Status"},
            "disposal_date": {"type": FieldType.DATE, "description": "Disposal date"},
            "journal_entry_for_scrap": {"type": FieldType.STRING, "max_length": 255, "description": "Scrap journal entry"},
            "insured_value": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Insured value"},
            "insurance_policy": {"type": FieldType.STRING, "max_length": 255, "description": "Insurance policy"},
            "warranty_expiry_date": {"type": FieldType.DATE, "description": "Warranty expiry date"},
            "serial_no": {"type": FieldType.STRING, "max_length": 255, "description": "Serial number"},
            "description": {"type": FieldType.STRING, "description": "Description"},
        },
        "required_fields": ["asset_name"],
        "unique_fields": ["serial_no"],
        "lookup_fields": ["id", "asset_name", "serial_no"],
        "dependencies": ["asset_categories"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
