"""Core entity definitions: contacts, customers, employees, departments, designations."""
from .base import FieldType, EntityConfig

CORE_ENTITIES: dict[str, EntityConfig] = {
    "contacts": {
        "model_name": "Contact",
        "display_name": "Contacts",
        "description": "Unified contacts (leads, prospects, customers, persons)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "normalizer": "name", "description": "Contact name"},
            "email": {"type": FieldType.EMAIL, "unique": True, "normalizer": "email", "description": "Email address"},
            "phone": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Phone number"},
            "mobile": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Mobile number"},
            "contact_type": {"type": FieldType.ENUM, "enum_values": ["lead", "prospect", "customer", "churned", "person"], "default": "customer", "description": "Contact type"},
            "category": {"type": FieldType.ENUM, "enum_values": ["residential", "business", "enterprise", "government", "non_profit"], "description": "Business category"},
            "status": {"type": FieldType.ENUM, "enum_values": ["active", "inactive", "suspended", "do_not_contact"], "default": "active", "description": "Contact status"},
            "company_name": {"type": FieldType.STRING, "max_length": 255, "description": "Company/organization name"},
            "address_line1": {"type": FieldType.STRING, "normalizer": "address", "description": "Street address line 1"},
            "address_line2": {"type": FieldType.STRING, "normalizer": "address", "description": "Street address line 2"},
            "city": {"type": FieldType.STRING, "max_length": 100, "description": "City"},
            "state": {"type": FieldType.STRING, "max_length": 100, "normalizer": "address", "description": "State/region"},
            "country": {"type": FieldType.STRING, "max_length": 100, "default": "Nigeria", "description": "Country"},
            "postal_code": {"type": FieldType.STRING, "max_length": 20, "description": "Postal/ZIP code"},
            "vat_id": {"type": FieldType.STRING, "max_length": 100, "description": "VAT/tax identification number"},
            "notes": {"type": FieldType.STRING, "description": "Additional notes"},
            "owner_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Assigned owner"},
        },
        "required_fields": ["name"],
        "unique_fields": ["email", "phone"],
        "lookup_fields": ["id", "email", "phone", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "customers": {
        "model_name": "Customer",
        "display_name": "Customers (Legacy)",
        "description": "Legacy customer records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "normalizer": "name", "description": "Customer name"},
            "email": {"type": FieldType.EMAIL, "normalizer": "email", "description": "Email address"},
            "phone": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Phone number"},
            "status": {"type": FieldType.ENUM, "enum_values": ["active", "inactive", "suspended", "prospect"], "default": "active", "description": "Customer status"},
            "street_1": {"type": FieldType.STRING, "description": "Street address line 1"},
            "street_2": {"type": FieldType.STRING, "description": "Street address line 2"},
            "city": {"type": FieldType.STRING, "max_length": 100, "description": "City"},
            "state": {"type": FieldType.STRING, "max_length": 100, "description": "State"},
            "zip": {"type": FieldType.STRING, "max_length": 20, "description": "ZIP/Postal code"},
            "country": {"type": FieldType.STRING, "max_length": 100, "default": "Nigeria", "description": "Country"},
        },
        "required_fields": ["name"],
        "unique_fields": ["email"],
        "lookup_fields": ["id", "email", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "employees": {
        "model_name": "Employee",
        "display_name": "Employees",
        "description": "Employee records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "normalizer": "name", "description": "Employee name"},
            "email": {"type": FieldType.EMAIL, "required": True, "unique": True, "normalizer": "email", "description": "Work email"},
            "personal_email": {"type": FieldType.EMAIL, "normalizer": "email", "description": "Personal email"},
            "phone": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Phone number"},
            "mobile": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Mobile number"},
            "designation": {"type": FieldType.STRING, "max_length": 100, "description": "Job title/designation"},
            "department": {"type": FieldType.STRING, "max_length": 100, "description": "Department name"},
            "employment_status": {"type": FieldType.ENUM, "enum_values": ["active", "inactive", "terminated", "on_leave"], "default": "active", "description": "Employment status"},
            "date_of_joining": {"type": FieldType.DATE, "description": "Date of joining"},
            "date_of_birth": {"type": FieldType.DATE, "description": "Date of birth"},
            "gender": {"type": FieldType.ENUM, "enum_values": ["male", "female", "other"], "description": "Gender"},
            "reports_to_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Manager"},
        },
        "required_fields": ["name", "email"],
        "unique_fields": ["email"],
        "lookup_fields": ["id", "email", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "departments": {
        "model_name": "Department",
        "display_name": "Departments",
        "description": "Organization departments",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Department name"},
            "parent_department": {"type": FieldType.STRING, "description": "Parent department name"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "designations": {
        "model_name": "Designation",
        "display_name": "Designations",
        "description": "Job titles/designations",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Designation name"},
            "description": {"type": FieldType.STRING, "description": "Description"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
