"""CRM entity definitions: leads, opportunities, activities, campaigns."""
from .base import FieldType, EntityConfig

CRM_ENTITIES: dict[str, EntityConfig] = {
    "leads": {
        "model_name": "Contact",
        "display_name": "Leads",
        "description": "Unified CRM leads (contact_type=lead)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "normalizer": "name", "description": "Lead name"},
            "first_name": {"type": FieldType.STRING, "max_length": 100, "description": "First name"},
            "last_name": {"type": FieldType.STRING, "max_length": 100, "description": "Last name"},
            "company_name": {"type": FieldType.STRING, "max_length": 255, "description": "Company name"},
            "email": {"type": FieldType.EMAIL, "normalizer": "email", "description": "Email"},
            "email_secondary": {"type": FieldType.EMAIL, "normalizer": "email", "description": "Secondary email"},
            "billing_email": {"type": FieldType.EMAIL, "normalizer": "email", "description": "Billing email"},
            "phone": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Phone"},
            "mobile": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Mobile"},
            "website": {"type": FieldType.STRING, "max_length": 255, "description": "Website"},
            "linkedin_url": {"type": FieldType.STRING, "max_length": 255, "description": "LinkedIn URL"},
            "contact_type": {"type": FieldType.ENUM, "enum_values": ["lead", "prospect", "customer", "churned", "person"], "default": "lead", "description": "Contact type"},
            "category": {"type": FieldType.ENUM, "enum_values": ["residential", "business", "enterprise", "government", "non_profit"], "description": "Business category"},
            "status": {"type": FieldType.ENUM, "enum_values": ["active", "inactive", "suspended", "do_not_contact"], "default": "active", "description": "Contact status"},
            "lead_qualification": {"type": FieldType.ENUM, "enum_values": ["unqualified", "cold", "warm", "hot", "qualified"], "description": "Lead qualification"},
            "lead_score": {"type": FieldType.INTEGER, "description": "Lead score"},
            "source": {"type": FieldType.STRING, "max_length": 255, "description": "Lead source"},
            "source_campaign": {"type": FieldType.STRING, "max_length": 255, "description": "Source campaign"},
            "referrer": {"type": FieldType.STRING, "max_length": 255, "description": "Referrer"},
            "industry": {"type": FieldType.STRING, "max_length": 255, "description": "Industry"},
            "market_segment": {"type": FieldType.STRING, "max_length": 255, "description": "Market segment"},
            "territory": {"type": FieldType.STRING, "max_length": 255, "description": "Territory"},
            "owner_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Owner"},
            "address_line1": {"type": FieldType.STRING, "normalizer": "address", "description": "Address line 1"},
            "address_line2": {"type": FieldType.STRING, "normalizer": "address", "description": "Address line 2"},
            "city": {"type": FieldType.STRING, "max_length": 100, "description": "City"},
            "state": {"type": FieldType.STRING, "max_length": 100, "description": "State"},
            "country": {"type": FieldType.STRING, "max_length": 100, "default": "Nigeria", "description": "Country"},
            "postal_code": {"type": FieldType.STRING, "max_length": 20, "description": "Postal code"},
            "notes": {"type": FieldType.STRING, "description": "Notes"},
        },
        "required_fields": ["name"],
        "unique_fields": ["email"],
        "lookup_fields": ["id", "email", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "lead_sources": {
        "model_name": "LeadSource",
        "display_name": "Lead Sources",
        "description": "Lead source master",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Source name"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "opportunity_stages": {
        "model_name": "OpportunityStage",
        "display_name": "Opportunity Stages",
        "description": "Sales pipeline stages",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Stage name"},
            "probability": {"type": FieldType.INTEGER, "description": "Win probability %"},
            "sequence": {"type": FieldType.INTEGER, "description": "Display sequence"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
            "is_won": {"type": FieldType.BOOLEAN, "default": False, "description": "Is won stage"},
            "is_lost": {"type": FieldType.BOOLEAN, "default": False, "description": "Is lost stage"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "opportunities": {
        "model_name": "Opportunity",
        "display_name": "Opportunities",
        "description": "Sales opportunities",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Opportunity name"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "lead_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "leads", "fk_lookup_fields": ["id", "email", "name"], "description": "Source lead"},
            "unified_contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Unified contact"},
            "stage_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "opportunity_stages", "fk_lookup_fields": ["id", "name"], "description": "Pipeline stage"},
            "owner_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Owner"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "won", "lost"], "default": "open", "description": "Status"},
            "deal_value": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Deal value"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "probability": {"type": FieldType.INTEGER, "description": "Win probability %"},
            "expected_close_date": {"type": FieldType.DATE, "description": "Expected close date"},
            "actual_close_date": {"type": FieldType.DATE, "description": "Actual close date"},
            "lost_reason": {"type": FieldType.STRING, "description": "Lost reason"},
            "competitor": {"type": FieldType.STRING, "description": "Competitor"},
            "source": {"type": FieldType.STRING, "max_length": 255, "description": "Source"},
            "campaign": {"type": FieldType.STRING, "max_length": 255, "description": "Campaign (name)"},
            "campaign_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "campaigns", "fk_lookup_fields": ["id", "name"], "description": "Campaign reference"},
            "notes": {"type": FieldType.STRING, "description": "Notes"},
        },
        "required_fields": ["name"],
        "unique_fields": [],
        "lookup_fields": ["id", "name"],
        "dependencies": ["opportunity_stages"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "activities": {
        "model_name": "Activity",
        "display_name": "CRM Activities",
        "description": "Sales activities (calls, meetings, emails)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "activity_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["call", "meeting", "email", "task", "note", "demo", "follow_up"], "description": "Activity type"},
            "subject": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Subject"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "lead_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "leads", "fk_lookup_fields": ["id", "email", "name"], "description": "Lead"},
            "opportunity_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "opportunities", "fk_lookup_fields": ["id", "name"], "description": "Opportunity"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "owner_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Owner"},
            "scheduled_at": {"type": FieldType.DATETIME, "description": "Scheduled date/time"},
            "completed_at": {"type": FieldType.DATETIME, "description": "Completed date/time"},
            "duration_minutes": {"type": FieldType.INTEGER, "description": "Duration in minutes"},
            "status": {"type": FieldType.ENUM, "enum_values": ["planned", "completed", "cancelled"], "default": "planned", "description": "Status"},
            "call_direction": {"type": FieldType.STRING, "max_length": 20, "description": "Call direction"},
            "call_outcome": {"type": FieldType.STRING, "max_length": 100, "description": "Call outcome"},
        },
        "required_fields": ["activity_type", "subject"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["opportunities"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "campaigns": {
        "model_name": "Campaign",
        "display_name": "Campaigns",
        "description": "Marketing campaigns",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Campaign name"},
            "campaign_type": {"type": FieldType.ENUM, "enum_values": ["email", "social", "advertising", "event", "referral", "other"], "default": "email", "description": "Campaign type"},
            "status": {"type": FieldType.ENUM, "enum_values": ["planned", "active", "completed", "cancelled"], "default": "planned", "description": "Status"},
            "start_date": {"type": FieldType.DATE, "description": "Start date"},
            "end_date": {"type": FieldType.DATE, "description": "End date"},
            "budget": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Budget"},
            "actual_cost": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Actual cost"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "expected_revenue": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Expected revenue"},
            "description": {"type": FieldType.STRING, "description": "Description"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
