"""Expense entity definitions: expenses, claims, cash advances."""
from .base import FieldType, EntityConfig

EXPENSE_ENTITIES: dict[str, EntityConfig] = {
    "expenses": {
        "model_name": "Expense",
        "display_name": "Expenses",
        "description": "Expense records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "expense_date": {"type": FieldType.DATE, "required": True, "description": "Expense date"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "category": {"type": FieldType.STRING, "max_length": 100, "description": "Category"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "project_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "projects", "fk_lookup_fields": ["id", "name"], "description": "Project"},
            "cost_center": {"type": FieldType.STRING, "max_length": 255, "description": "Cost center"},
            "is_billable": {"type": FieldType.BOOLEAN, "default": False, "description": "Is billable to customer"},
            "payment_mode": {"type": FieldType.STRING, "max_length": 100, "description": "Payment mode"},
            "reference_number": {"type": FieldType.STRING, "max_length": 255, "description": "Reference number"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "approved", "rejected", "paid"], "default": "draft", "description": "Status"},
        },
        "required_fields": ["expense_date", "amount"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "expense_claims": {
        "model_name": "ExpenseClaim",
        "display_name": "Expense Claims",
        "description": "Employee expense claims/reimbursements",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "claim_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Claim number"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "expense_approver_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Approver"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "total_claimed_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total claimed amount"},
            "total_sanctioned_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total sanctioned amount"},
            "total_advance_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Advance amount used"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "approved", "rejected", "paid", "cancelled"], "default": "draft", "description": "Status"},
            "payable_account": {"type": FieldType.STRING, "max_length": 255, "description": "Payable GL account"},
            "mode_of_payment": {"type": FieldType.STRING, "max_length": 100, "description": "Payment mode"},
        },
        "required_fields": ["employee_id", "posting_date"],
        "unique_fields": ["claim_number"],
        "lookup_fields": ["id", "claim_number"],
        "dependencies": ["employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "expense_claim_lines": {
        "model_name": "ExpenseClaimLine",
        "display_name": "Expense Claim Lines",
        "description": "Individual expense claim line items",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "expense_claim_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "expense_claims", "fk_lookup_fields": ["id", "claim_number"], "description": "Expense claim"},
            "expense_date": {"type": FieldType.DATE, "required": True, "description": "Expense date"},
            "expense_type": {"type": FieldType.STRING, "max_length": 100, "description": "Expense type"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "claim_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Claimed amount"},
            "sanctioned_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Sanctioned amount"},
            "cost_center": {"type": FieldType.STRING, "max_length": 255, "description": "Cost center"},
            "project_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "projects", "fk_lookup_fields": ["id", "name"], "description": "Project"},
            "default_account": {"type": FieldType.STRING, "max_length": 255, "description": "Expense GL account"},
        },
        "required_fields": ["expense_claim_id", "expense_date", "claim_amount"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["expense_claims"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "cash_advances": {
        "model_name": "CashAdvance",
        "display_name": "Cash Advances",
        "description": "Employee cash advance requests",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "advance_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Advance number"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "purpose": {"type": FieldType.STRING, "required": True, "description": "Purpose of advance"},
            "advance_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Advance amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "advance_account": {"type": FieldType.STRING, "max_length": 255, "description": "Advance GL account"},
            "mode_of_payment": {"type": FieldType.STRING, "max_length": 100, "description": "Payment mode"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "approved", "rejected", "paid", "claimed", "returned", "cancelled"], "default": "draft", "description": "Status"},
            "claimed_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Amount claimed against"},
            "return_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Amount returned"},
        },
        "required_fields": ["employee_id", "purpose", "advance_amount", "posting_date"],
        "unique_fields": ["advance_number"],
        "lookup_fields": ["id", "advance_number"],
        "dependencies": ["employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
