"""HR entity definitions: leave, attendance, payroll, appraisals, training."""
from .base import FieldType, EntityConfig

HR_ENTITIES: dict[str, EntityConfig] = {
    # =========================================================================
    # LEAVE MANAGEMENT (7 entities)
    # =========================================================================
    "leave_types": {
        "model_name": "LeaveType",
        "display_name": "Leave Types",
        "description": "Leave type master (annual, sick, etc.)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "leave_type_name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Leave type name"},
            "max_continuous_days_allowed": {"type": FieldType.INTEGER, "description": "Max continuous days"},
            "is_carry_forward": {"type": FieldType.BOOLEAN, "default": False, "description": "Allow carry forward"},
            "is_without_pay": {"type": FieldType.BOOLEAN, "default": False, "description": "Is unpaid leave"},
            "allow_negative": {"type": FieldType.BOOLEAN, "default": False, "description": "Allow negative balance"},
            "include_holidays_in_total": {"type": FieldType.BOOLEAN, "default": False, "description": "Include holidays in count"},
            "is_compensatory": {"type": FieldType.BOOLEAN, "default": False, "description": "Is compensatory leave"},
            "max_days_allowed": {"type": FieldType.DECIMAL, "description": "Maximum days allowed per year"},
        },
        "required_fields": ["leave_type_name"],
        "unique_fields": ["leave_type_name"],
        "lookup_fields": ["id", "leave_type_name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "holiday_lists": {
        "model_name": "HolidayList",
        "display_name": "Holiday Lists",
        "description": "Holiday calendar definitions",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "holiday_list_name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Holiday list name"},
            "from_date": {"type": FieldType.DATE, "required": True, "description": "Start date"},
            "to_date": {"type": FieldType.DATE, "required": True, "description": "End date"},
            "weekly_off": {"type": FieldType.STRING, "max_length": 50, "default": "Sunday", "description": "Weekly off day"},
        },
        "required_fields": ["holiday_list_name", "from_date", "to_date"],
        "unique_fields": ["holiday_list_name"],
        "lookup_fields": ["id", "holiday_list_name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "holidays": {
        "model_name": "Holiday",
        "display_name": "Holidays",
        "description": "Individual holiday entries",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "holiday_list_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "holiday_lists", "fk_lookup_fields": ["id", "holiday_list_name"], "description": "Holiday list"},
            "holiday_date": {"type": FieldType.DATE, "required": True, "description": "Holiday date"},
            "description": {"type": FieldType.STRING, "max_length": 255, "description": "Holiday description"},
        },
        "required_fields": ["holiday_list_id", "holiday_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["holiday_lists"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "leave_policies": {
        "model_name": "LeavePolicy",
        "display_name": "Leave Policies",
        "description": "Leave policy definitions",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Policy name"},
            "is_default": {"type": FieldType.BOOLEAN, "default": False, "description": "Is default policy"},
            "description": {"type": FieldType.STRING, "description": "Policy description"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "leave_policy_details": {
        "model_name": "LeavePolicyDetail",
        "display_name": "Leave Policy Details",
        "description": "Leave policy line items (leave type allocations)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "leave_policy_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "leave_policies", "fk_lookup_fields": ["id", "name"], "description": "Leave policy"},
            "leave_type_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "leave_types", "fk_lookup_fields": ["id", "leave_type_name"], "description": "Leave type"},
            "annual_allocation": {"type": FieldType.DECIMAL, "required": True, "description": "Annual allocation days"},
        },
        "required_fields": ["leave_policy_id", "leave_type_id", "annual_allocation"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["leave_policies", "leave_types"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "leave_allocations": {
        "model_name": "LeaveAllocation",
        "display_name": "Leave Allocations",
        "description": "Employee leave balance allocations",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "leave_type_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "leave_types", "fk_lookup_fields": ["id", "leave_type_name"], "description": "Leave type"},
            "from_date": {"type": FieldType.DATE, "required": True, "description": "Period start date"},
            "to_date": {"type": FieldType.DATE, "required": True, "description": "Period end date"},
            "new_leaves_allocated": {"type": FieldType.DECIMAL, "required": True, "description": "New leaves allocated"},
            "carry_forward": {"type": FieldType.DECIMAL, "default": 0, "description": "Carry forward from previous period"},
            "total_leaves_allocated": {"type": FieldType.DECIMAL, "description": "Total allocated (new + carry forward)"},
        },
        "required_fields": ["employee_id", "leave_type_id", "from_date", "to_date", "new_leaves_allocated"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees", "leave_types"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "leave_applications": {
        "model_name": "LeaveApplication",
        "display_name": "Leave Applications",
        "description": "Employee leave requests",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "leave_type_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "leave_types", "fk_lookup_fields": ["id", "leave_type_name"], "description": "Leave type"},
            "from_date": {"type": FieldType.DATE, "required": True, "description": "Leave start date"},
            "to_date": {"type": FieldType.DATE, "required": True, "description": "Leave end date"},
            "half_day": {"type": FieldType.BOOLEAN, "default": False, "description": "Is half day"},
            "total_leave_days": {"type": FieldType.DECIMAL, "description": "Total leave days"},
            "reason": {"type": FieldType.STRING, "description": "Leave reason"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "approved", "rejected", "cancelled"], "default": "open", "description": "Application status"},
        },
        "required_fields": ["employee_id", "leave_type_id", "from_date", "to_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees", "leave_types"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    # =========================================================================
    # ATTENDANCE (4 entities)
    # =========================================================================
    "shift_types": {
        "model_name": "ShiftType",
        "display_name": "Shift Types",
        "description": "Work shift definitions",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Shift name"},
            "start_time": {"type": FieldType.STRING, "max_length": 10, "description": "Start time (HH:MM)"},
            "end_time": {"type": FieldType.STRING, "max_length": 10, "description": "End time (HH:MM)"},
            "working_hours": {"type": FieldType.DECIMAL, "description": "Working hours per day"},
            "late_entry_grace_period": {"type": FieldType.INTEGER, "description": "Late entry grace period (minutes)"},
            "early_exit_grace_period": {"type": FieldType.INTEGER, "description": "Early exit grace period (minutes)"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "shift_assignments": {
        "model_name": "ShiftAssignment",
        "display_name": "Shift Assignments",
        "description": "Employee shift assignments",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "shift_type_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "shift_types", "fk_lookup_fields": ["id", "name"], "description": "Shift type"},
            "start_date": {"type": FieldType.DATE, "required": True, "description": "Assignment start date"},
            "end_date": {"type": FieldType.DATE, "description": "Assignment end date"},
            "status": {"type": FieldType.ENUM, "enum_values": ["active", "inactive"], "default": "active", "description": "Status"},
        },
        "required_fields": ["employee_id", "shift_type_id", "start_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees", "shift_types"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "attendances": {
        "model_name": "Attendance",
        "display_name": "Attendance Records",
        "description": "Daily attendance records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "attendance_date": {"type": FieldType.DATE, "required": True, "description": "Attendance date"},
            "status": {"type": FieldType.ENUM, "required": True, "enum_values": ["present", "absent", "on_leave", "half_day", "work_from_home"], "description": "Attendance status"},
            "in_time": {"type": FieldType.DATETIME, "description": "Check-in time"},
            "out_time": {"type": FieldType.DATETIME, "description": "Check-out time"},
            "working_hours": {"type": FieldType.DECIMAL, "description": "Total working hours"},
            "late_entry": {"type": FieldType.BOOLEAN, "default": False, "description": "Was late entry"},
            "early_exit": {"type": FieldType.BOOLEAN, "default": False, "description": "Was early exit"},
            "shift_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "shift_types", "fk_lookup_fields": ["id", "name"], "description": "Shift"},
        },
        "required_fields": ["employee_id", "attendance_date", "status"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "attendance_requests": {
        "model_name": "AttendanceRequest",
        "display_name": "Attendance Requests",
        "description": "Attendance correction requests",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "attendance_date": {"type": FieldType.DATE, "required": True, "description": "Attendance date"},
            "reason": {"type": FieldType.STRING, "required": True, "description": "Request reason"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "approved", "rejected"], "default": "open", "description": "Request status"},
        },
        "required_fields": ["employee_id", "attendance_date", "reason"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    # =========================================================================
    # PAYROLL (9 entities)
    # =========================================================================
    "salary_components": {
        "model_name": "SalaryComponent",
        "display_name": "Salary Components",
        "description": "Earning and deduction types",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Component name"},
            "type": {"type": FieldType.ENUM, "required": True, "enum_values": ["earning", "deduction"], "description": "Component type"},
            "abbr": {"type": FieldType.STRING, "max_length": 50, "description": "Abbreviation"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "is_tax_applicable": {"type": FieldType.BOOLEAN, "default": True, "description": "Is taxable"},
            "is_payable": {"type": FieldType.BOOLEAN, "default": True, "description": "Is payable"},
            "depends_on_payment_days": {"type": FieldType.BOOLEAN, "default": True, "description": "Pro-rate on attendance"},
            "statistical_component": {"type": FieldType.BOOLEAN, "default": False, "description": "Statistical only (not included in pay)"},
            "formula": {"type": FieldType.STRING, "description": "Calculation formula"},
            "amount_based_on_formula": {"type": FieldType.BOOLEAN, "default": False, "description": "Use formula for amount"},
            "condition": {"type": FieldType.STRING, "description": "Conditional expression"},
        },
        "required_fields": ["name", "type"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name", "abbr"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_structures": {
        "model_name": "SalaryStructure",
        "display_name": "Salary Structures",
        "description": "Pay structure templates",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Structure name"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
            "payroll_frequency": {"type": FieldType.ENUM, "enum_values": ["monthly", "biweekly", "weekly", "daily"], "default": "monthly", "description": "Payroll frequency"},
            "payment_account": {"type": FieldType.STRING, "max_length": 255, "description": "Payment GL account"},
            "mode_of_payment": {"type": FieldType.STRING, "max_length": 100, "description": "Payment mode"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_structure_earnings": {
        "model_name": "SalaryStructureEarning",
        "display_name": "Salary Structure Earnings",
        "description": "Salary structure earning lines",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "salary_structure_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_structures", "fk_lookup_fields": ["id", "name"], "description": "Salary structure"},
            "salary_component_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_components", "fk_lookup_fields": ["id", "name"], "description": "Salary component"},
            "amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Fixed amount"},
            "formula": {"type": FieldType.STRING, "description": "Formula (if not fixed)"},
            "amount_based_on_formula": {"type": FieldType.BOOLEAN, "default": False, "description": "Use formula"},
            "idx": {"type": FieldType.INTEGER, "description": "Display order"},
        },
        "required_fields": ["salary_structure_id", "salary_component_id"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["salary_structures", "salary_components"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_structure_deductions": {
        "model_name": "SalaryStructureDeduction",
        "display_name": "Salary Structure Deductions",
        "description": "Salary structure deduction lines",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "salary_structure_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_structures", "fk_lookup_fields": ["id", "name"], "description": "Salary structure"},
            "salary_component_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_components", "fk_lookup_fields": ["id", "name"], "description": "Salary component"},
            "amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Fixed amount"},
            "formula": {"type": FieldType.STRING, "description": "Formula (if not fixed)"},
            "amount_based_on_formula": {"type": FieldType.BOOLEAN, "default": False, "description": "Use formula"},
            "idx": {"type": FieldType.INTEGER, "description": "Display order"},
        },
        "required_fields": ["salary_structure_id", "salary_component_id"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["salary_structures", "salary_components"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_structure_assignments": {
        "model_name": "SalaryStructureAssignment",
        "display_name": "Salary Structure Assignments",
        "description": "Employee-structure assignments",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "salary_structure_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_structures", "fk_lookup_fields": ["id", "name"], "description": "Salary structure"},
            "from_date": {"type": FieldType.DATE, "required": True, "description": "Effective from date"},
            "to_date": {"type": FieldType.DATE, "description": "Effective to date"},
            "base": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Base salary amount"},
            "variable": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Variable component"},
            "income_tax_slab": {"type": FieldType.STRING, "max_length": 255, "description": "Tax slab"},
        },
        "required_fields": ["employee_id", "salary_structure_id", "from_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees", "salary_structures"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "payroll_entries": {
        "model_name": "PayrollEntry",
        "display_name": "Payroll Entries",
        "description": "Payroll run batches",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "payroll_frequency": {"type": FieldType.ENUM, "enum_values": ["monthly", "biweekly", "weekly", "daily"], "default": "monthly", "description": "Payroll frequency"},
            "start_date": {"type": FieldType.DATE, "required": True, "description": "Period start date"},
            "end_date": {"type": FieldType.DATE, "required": True, "description": "Period end date"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "approved", "cancelled"], "default": "draft", "description": "Status"},
            "salary_slips_created": {"type": FieldType.INTEGER, "description": "Number of slips created"},
            "salary_slips_submitted": {"type": FieldType.INTEGER, "description": "Number of slips submitted"},
        },
        "required_fields": ["posting_date", "start_date", "end_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_slips": {
        "model_name": "SalarySlip",
        "display_name": "Salary Slips",
        "description": "Individual payslips",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "payroll_entry_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "payroll_entries", "fk_lookup_fields": ["id"], "description": "Payroll entry"},
            "salary_structure_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "salary_structures", "fk_lookup_fields": ["id", "name"], "description": "Salary structure"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "start_date": {"type": FieldType.DATE, "required": True, "description": "Period start date"},
            "end_date": {"type": FieldType.DATE, "required": True, "description": "Period end date"},
            "gross_pay": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Gross pay"},
            "total_deduction": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total deductions"},
            "net_pay": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Net pay"},
            "payment_days": {"type": FieldType.DECIMAL, "description": "Payment days"},
            "leave_without_pay": {"type": FieldType.DECIMAL, "default": 0, "description": "Leave without pay days"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "cancelled"], "default": "draft", "description": "Status"},
        },
        "required_fields": ["employee_id", "posting_date", "start_date", "end_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_slip_earnings": {
        "model_name": "SalarySlipEarning",
        "display_name": "Salary Slip Earnings",
        "description": "Payslip earning lines",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "salary_slip_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_slips", "fk_lookup_fields": ["id"], "description": "Salary slip"},
            "salary_component_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_components", "fk_lookup_fields": ["id", "name"], "description": "Salary component"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Amount"},
            "default_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Default amount"},
            "additional_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Additional amount"},
        },
        "required_fields": ["salary_slip_id", "salary_component_id", "amount"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["salary_slips", "salary_components"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "salary_slip_deductions": {
        "model_name": "SalarySlipDeduction",
        "display_name": "Salary Slip Deductions",
        "description": "Payslip deduction lines",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "salary_slip_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_slips", "fk_lookup_fields": ["id"], "description": "Salary slip"},
            "salary_component_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "salary_components", "fk_lookup_fields": ["id", "name"], "description": "Salary component"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Amount"},
            "default_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Default amount"},
            "additional_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Additional amount"},
        },
        "required_fields": ["salary_slip_id", "salary_component_id", "amount"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["salary_slips", "salary_components"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    # =========================================================================
    # APPRAISALS (4 entities)
    # =========================================================================
    "appraisal_templates": {
        "model_name": "AppraisalTemplate",
        "display_name": "Appraisal Templates",
        "description": "Appraisal form templates",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "template_title": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Template title"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
        },
        "required_fields": ["template_title"],
        "unique_fields": ["template_title"],
        "lookup_fields": ["id", "template_title"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "appraisal_template_goals": {
        "model_name": "AppraisalTemplateGoal",
        "display_name": "Appraisal Template Goals",
        "description": "Template KRA items",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "template_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "appraisal_templates", "fk_lookup_fields": ["id", "template_title"], "description": "Appraisal template"},
            "kra": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Key result area"},
            "per_weightage": {"type": FieldType.DECIMAL, "description": "Percentage weightage"},
            "idx": {"type": FieldType.INTEGER, "description": "Display order"},
        },
        "required_fields": ["template_id", "kra"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["appraisal_templates"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "appraisals": {
        "model_name": "Appraisal",
        "display_name": "Appraisals",
        "description": "Employee appraisals",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "template_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "appraisal_templates", "fk_lookup_fields": ["id", "template_title"], "description": "Appraisal template"},
            "start_date": {"type": FieldType.DATE, "required": True, "description": "Appraisal period start"},
            "end_date": {"type": FieldType.DATE, "required": True, "description": "Appraisal period end"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "completed", "cancelled"], "default": "draft", "description": "Status"},
            "total_score": {"type": FieldType.DECIMAL, "description": "Total score"},
            "final_score": {"type": FieldType.DECIMAL, "description": "Final weighted score"},
            "remarks": {"type": FieldType.STRING, "description": "Remarks"},
        },
        "required_fields": ["employee_id", "start_date", "end_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "appraisal_goals": {
        "model_name": "AppraisalGoal",
        "display_name": "Appraisal Goals",
        "description": "Appraisal KRA scores",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "appraisal_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "appraisals", "fk_lookup_fields": ["id"], "description": "Appraisal"},
            "kra": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Key result area"},
            "per_weightage": {"type": FieldType.DECIMAL, "description": "Percentage weightage"},
            "score": {"type": FieldType.DECIMAL, "description": "Score (0-5)"},
            "score_earned": {"type": FieldType.DECIMAL, "description": "Weighted score earned"},
            "idx": {"type": FieldType.INTEGER, "description": "Display order"},
        },
        "required_fields": ["appraisal_id", "kra"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["appraisals"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    # =========================================================================
    # TRAINING (4 entities)
    # =========================================================================
    "training_programs": {
        "model_name": "TrainingProgram",
        "display_name": "Training Programs",
        "description": "Training program master",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Program name"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "is_mandatory": {"type": FieldType.BOOLEAN, "default": False, "description": "Is mandatory"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "training_events": {
        "model_name": "TrainingEvent",
        "display_name": "Training Events",
        "description": "Scheduled training sessions",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "event_name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Event name"},
            "training_program_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "training_programs", "fk_lookup_fields": ["id", "name"], "description": "Training program"},
            "type": {"type": FieldType.ENUM, "enum_values": ["seminar", "theory", "workshop", "conference", "online", "other"], "default": "seminar", "description": "Event type"},
            "level": {"type": FieldType.ENUM, "enum_values": ["beginner", "intermediate", "expert", "all"], "default": "all", "description": "Level"},
            "trainer_name": {"type": FieldType.STRING, "max_length": 255, "description": "Trainer name"},
            "supplier": {"type": FieldType.STRING, "max_length": 255, "description": "Training provider"},
            "start_time": {"type": FieldType.DATETIME, "description": "Start time"},
            "end_time": {"type": FieldType.DATETIME, "description": "End time"},
            "introduction": {"type": FieldType.STRING, "description": "Introduction text"},
            "status": {"type": FieldType.ENUM, "enum_values": ["scheduled", "completed", "cancelled"], "default": "scheduled", "description": "Status"},
        },
        "required_fields": ["event_name"],
        "unique_fields": [],
        "lookup_fields": ["id", "event_name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "training_event_employees": {
        "model_name": "TrainingEventEmployee",
        "display_name": "Training Participants",
        "description": "Training event participants",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "training_event_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "training_events", "fk_lookup_fields": ["id", "event_name"], "description": "Training event"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "status": {"type": FieldType.ENUM, "enum_values": ["invited", "confirmed", "attended", "absent"], "default": "invited", "description": "Participation status"},
            "feedback": {"type": FieldType.STRING, "description": "Employee feedback"},
        },
        "required_fields": ["training_event_id", "employee_id"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["training_events", "employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "training_results": {
        "model_name": "TrainingResult",
        "display_name": "Training Results",
        "description": "Training completion records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "training_event_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "training_events", "fk_lookup_fields": ["id", "event_name"], "description": "Training event"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Employee"},
            "hours": {"type": FieldType.DECIMAL, "description": "Hours attended"},
            "grade": {"type": FieldType.STRING, "max_length": 50, "description": "Grade achieved"},
            "result": {"type": FieldType.ENUM, "enum_values": ["passed", "failed", "pending"], "default": "pending", "description": "Result"},
            "comments": {"type": FieldType.STRING, "description": "Comments"},
        },
        "required_fields": ["training_event_id", "employee_id"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["training_events", "employees"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
