"""Inventory entity definitions: items, warehouses, stock entries."""
from .base import FieldType, EntityConfig

INVENTORY_ENTITIES: dict[str, EntityConfig] = {
    "items": {
        "model_name": "Item",
        "display_name": "Items",
        "description": "Inventory items/products",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "item_code": {"type": FieldType.STRING, "unique": True, "max_length": 50, "description": "Item code/SKU"},
            "item_name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Item name"},
            "item_group": {"type": FieldType.STRING, "max_length": 100, "description": "Item group/category"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "stock_uom": {"type": FieldType.STRING, "max_length": 50, "default": "Nos", "description": "Unit of measure"},
            "is_stock_item": {"type": FieldType.BOOLEAN, "default": True, "description": "Is stock item"},
            "is_sales_item": {"type": FieldType.BOOLEAN, "default": True, "description": "Is sales item"},
            "is_purchase_item": {"type": FieldType.BOOLEAN, "default": True, "description": "Is purchase item"},
            "standard_rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Standard selling price"},
            "valuation_rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Valuation rate"},
            "min_order_qty": {"type": FieldType.DECIMAL, "description": "Minimum order quantity"},
            "safety_stock": {"type": FieldType.DECIMAL, "description": "Safety stock level"},
            "has_batch_no": {"type": FieldType.BOOLEAN, "default": False, "description": "Track by batch"},
            "has_serial_no": {"type": FieldType.BOOLEAN, "default": False, "description": "Track by serial"},
            "warranty_period": {"type": FieldType.INTEGER, "description": "Warranty period (days)"},
        },
        "required_fields": ["item_name"],
        "unique_fields": ["item_code"],
        "lookup_fields": ["id", "item_code", "item_name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "warehouses": {
        "model_name": "Warehouse",
        "display_name": "Warehouses",
        "description": "Storage locations",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Warehouse name"},
            "parent_warehouse": {"type": FieldType.STRING, "description": "Parent warehouse name"},
            "company": {"type": FieldType.STRING, "max_length": 255, "description": "Company"},
            "is_group": {"type": FieldType.BOOLEAN, "default": False, "description": "Is group"},
            "address": {"type": FieldType.STRING, "description": "Address"},
            "city": {"type": FieldType.STRING, "max_length": 100, "description": "City"},
            "state": {"type": FieldType.STRING, "max_length": 100, "description": "State"},
            "country": {"type": FieldType.STRING, "max_length": 100, "default": "Nigeria", "description": "Country"},
            "warehouse_type": {"type": FieldType.ENUM, "enum_values": ["warehouse", "transit", "rejected"], "default": "warehouse", "description": "Warehouse type"},
            "disabled": {"type": FieldType.BOOLEAN, "default": False, "description": "Is disabled"},
        },
        "required_fields": ["name"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_entries": {
        "model_name": "StockEntry",
        "display_name": "Stock Entries",
        "description": "Inventory transactions (receipts, issues, transfers)",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "stock_entry_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["material_receipt", "material_issue", "material_transfer", "material_consumption", "manufacture", "repack", "send_to_subcontractor", "return"], "description": "Entry type"},
            "posting_date": {"type": FieldType.DATETIME, "required": True, "description": "Posting date"},
            "from_warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Source warehouse"},
            "to_warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Target warehouse"},
            "total_value": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total value"},
            "reference_doctype": {"type": FieldType.STRING, "max_length": 100, "description": "Reference document type"},
            "reference_name": {"type": FieldType.STRING, "max_length": 255, "description": "Reference document ID"},
            "remarks": {"type": FieldType.STRING, "description": "Remarks"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "cancelled"], "default": "draft", "description": "Status"},
        },
        "required_fields": ["stock_entry_type", "posting_date"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["warehouses"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_entry_details": {
        "model_name": "StockEntryDetail",
        "display_name": "Stock Entry Details",
        "description": "Stock entry line items",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "stock_entry_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "stock_entries", "fk_lookup_fields": ["id"], "description": "Stock entry"},
            "item_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "items", "fk_lookup_fields": ["id", "item_code"], "description": "Item"},
            "qty": {"type": FieldType.DECIMAL, "required": True, "description": "Quantity"},
            "uom": {"type": FieldType.STRING, "max_length": 50, "description": "Unit of measure"},
            "basic_rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Rate per unit"},
            "basic_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Amount"},
            "batch_no": {"type": FieldType.STRING, "max_length": 100, "description": "Batch number"},
            "serial_no": {"type": FieldType.STRING, "description": "Serial numbers (newline separated)"},
            "from_warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Source warehouse"},
            "to_warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Target warehouse"},
        },
        "required_fields": ["stock_entry_id", "item_id", "qty"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["stock_entries", "items"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_ledger_entries": {
        "model_name": "StockLedgerEntry",
        "display_name": "Stock Ledger Entries",
        "description": "Stock audit trail/ledger",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "item_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "items", "fk_lookup_fields": ["id", "item_code"], "description": "Item"},
            "warehouse_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Warehouse"},
            "posting_date": {"type": FieldType.DATETIME, "required": True, "description": "Posting date"},
            "actual_qty": {"type": FieldType.DECIMAL, "required": True, "description": "Quantity change (+/-)"},
            "qty_after_transaction": {"type": FieldType.DECIMAL, "description": "Balance after transaction"},
            "incoming_rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Incoming rate"},
            "outgoing_rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Outgoing rate"},
            "stock_value": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Stock value after transaction"},
            "voucher_type": {"type": FieldType.STRING, "max_length": 100, "description": "Voucher type"},
            "voucher_no": {"type": FieldType.STRING, "max_length": 255, "description": "Voucher number"},
            "batch_no": {"type": FieldType.STRING, "max_length": 100, "description": "Batch number"},
            "serial_no": {"type": FieldType.STRING, "description": "Serial number"},
        },
        "required_fields": ["item_id", "warehouse_id", "posting_date", "actual_qty"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["items", "warehouses"],
        "supports_upsert": False,
        "supports_rollback": False,
    },

    "batches": {
        "model_name": "Batch",
        "display_name": "Batches",
        "description": "Batch tracking for inventory",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "batch_id": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 100, "description": "Batch ID"},
            "item_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "items", "fk_lookup_fields": ["id", "item_code"], "description": "Item"},
            "manufacturing_date": {"type": FieldType.DATE, "description": "Manufacturing date"},
            "expiry_date": {"type": FieldType.DATE, "description": "Expiry date"},
            "batch_qty": {"type": FieldType.DECIMAL, "description": "Batch quantity"},
            "reference_doctype": {"type": FieldType.STRING, "max_length": 100, "description": "Reference document type"},
            "reference_name": {"type": FieldType.STRING, "max_length": 255, "description": "Reference document ID"},
            "description": {"type": FieldType.STRING, "description": "Description"},
        },
        "required_fields": ["batch_id", "item_id"],
        "unique_fields": ["batch_id"],
        "lookup_fields": ["id", "batch_id"],
        "dependencies": ["items"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "serial_numbers": {
        "model_name": "SerialNo",
        "display_name": "Serial Numbers",
        "description": "Serial number tracking",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "serial_no": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Serial number"},
            "item_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "items", "fk_lookup_fields": ["id", "item_code"], "description": "Item"},
            "warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Current warehouse"},
            "batch_no": {"type": FieldType.STRING, "max_length": 100, "description": "Batch number"},
            "purchase_date": {"type": FieldType.DATE, "description": "Purchase date"},
            "purchase_rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Purchase rate"},
            "delivery_date": {"type": FieldType.DATE, "description": "Delivery date"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer (if sold)"},
            "warranty_expiry_date": {"type": FieldType.DATE, "description": "Warranty expiry date"},
            "status": {"type": FieldType.ENUM, "enum_values": ["inactive", "active", "delivered", "expired"], "default": "inactive", "description": "Status"},
        },
        "required_fields": ["serial_no", "item_id"],
        "unique_fields": ["serial_no"],
        "lookup_fields": ["id", "serial_no"],
        "dependencies": ["items"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_receipts": {
        "model_name": "StockReceipt",
        "display_name": "Stock Receipts",
        "description": "Purchase receipts",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "receipt_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Receipt number"},
            "supplier_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "suppliers", "fk_lookup_fields": ["id", "email", "name"], "description": "Supplier"},
            "purchase_invoice_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "purchase_invoices", "fk_lookup_fields": ["id", "bill_number"], "description": "Purchase invoice"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Target warehouse"},
            "total_qty": {"type": FieldType.DECIMAL, "description": "Total quantity"},
            "total_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total amount"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "to_bill", "completed", "cancelled"], "default": "draft", "description": "Status"},
        },
        "required_fields": ["posting_date"],
        "unique_fields": ["receipt_number"],
        "lookup_fields": ["id", "receipt_number"],
        "dependencies": ["warehouses"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_receipt_items": {
        "model_name": "StockReceiptItem",
        "display_name": "Stock Receipt Items",
        "description": "Receipt line items",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "stock_receipt_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "stock_receipts", "fk_lookup_fields": ["id", "receipt_number"], "description": "Stock receipt"},
            "item_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "items", "fk_lookup_fields": ["id", "item_code"], "description": "Item"},
            "qty": {"type": FieldType.DECIMAL, "required": True, "description": "Quantity"},
            "uom": {"type": FieldType.STRING, "max_length": 50, "description": "Unit of measure"},
            "rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Rate"},
            "amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Amount"},
            "batch_no": {"type": FieldType.STRING, "max_length": 100, "description": "Batch number"},
            "serial_no": {"type": FieldType.STRING, "description": "Serial numbers"},
            "warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Target warehouse"},
        },
        "required_fields": ["stock_receipt_id", "item_id", "qty"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["stock_receipts", "items"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_issues": {
        "model_name": "StockIssue",
        "display_name": "Stock Issues",
        "description": "Sales/delivery issues",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "issue_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Issue number"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "invoice_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "invoices", "fk_lookup_fields": ["id", "invoice_number"], "description": "Sales invoice"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Source warehouse"},
            "total_qty": {"type": FieldType.DECIMAL, "description": "Total quantity"},
            "total_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total amount"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "to_bill", "completed", "cancelled", "return_issued"], "default": "draft", "description": "Status"},
        },
        "required_fields": ["posting_date"],
        "unique_fields": ["issue_number"],
        "lookup_fields": ["id", "issue_number"],
        "dependencies": ["warehouses"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "stock_issue_items": {
        "model_name": "StockIssueItem",
        "display_name": "Stock Issue Items",
        "description": "Issue line items",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "stock_issue_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "stock_issues", "fk_lookup_fields": ["id", "issue_number"], "description": "Stock issue"},
            "item_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "items", "fk_lookup_fields": ["id", "item_code"], "description": "Item"},
            "qty": {"type": FieldType.DECIMAL, "required": True, "description": "Quantity"},
            "uom": {"type": FieldType.STRING, "max_length": 50, "description": "Unit of measure"},
            "rate": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Rate"},
            "amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Amount"},
            "batch_no": {"type": FieldType.STRING, "max_length": 100, "description": "Batch number"},
            "serial_no": {"type": FieldType.STRING, "description": "Serial numbers"},
            "warehouse_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Source warehouse"},
        },
        "required_fields": ["stock_issue_id", "item_id", "qty"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["stock_issues", "items"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "transfer_requests": {
        "model_name": "TransferRequest",
        "display_name": "Transfer Requests",
        "description": "Inter-warehouse transfer requests",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "request_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Request number"},
            "from_warehouse_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Source warehouse"},
            "to_warehouse_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "warehouses", "fk_lookup_fields": ["id", "name"], "description": "Target warehouse"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Request date"},
            "required_date": {"type": FieldType.DATE, "description": "Required by date"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "pending", "in_transit", "completed", "cancelled"], "default": "draft", "description": "Status"},
            "remarks": {"type": FieldType.STRING, "description": "Remarks"},
        },
        "required_fields": ["from_warehouse_id", "to_warehouse_id", "posting_date"],
        "unique_fields": ["request_number"],
        "lookup_fields": ["id", "request_number"],
        "dependencies": ["warehouses"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
