"""Project entity definitions: projects, tasks."""
from .base import FieldType, EntityConfig

PROJECT_ENTITIES: dict[str, EntityConfig] = {
    "projects": {
        "model_name": "Project",
        "display_name": "Projects",
        "description": "Project records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Project name"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "project_manager_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Project manager"},
            "department": {"type": FieldType.STRING, "max_length": 100, "description": "Department"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "completed", "cancelled", "on_hold"], "default": "open", "description": "Status"},
            "priority": {"type": FieldType.ENUM, "enum_values": ["low", "medium", "high"], "default": "medium", "description": "Priority"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
            "percent_complete": {"type": FieldType.DECIMAL, "default": 0, "description": "Percent complete"},
            "expected_start": {"type": FieldType.DATE, "description": "Expected start date"},
            "expected_end": {"type": FieldType.DATE, "description": "Expected end date"},
            "actual_start": {"type": FieldType.DATE, "description": "Actual start date"},
            "actual_end": {"type": FieldType.DATE, "description": "Actual end date"},
            "estimated_cost": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Estimated cost"},
            "total_costing_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total costing amount"},
            "total_billing_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total billing amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "cost_center": {"type": FieldType.STRING, "max_length": 255, "description": "Cost center"},
            "description": {"type": FieldType.STRING, "description": "Project description"},
            "notes": {"type": FieldType.STRING, "description": "Notes"},
        },
        "required_fields": ["name"],
        "unique_fields": [],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tasks": {
        "model_name": "Task",
        "display_name": "Tasks",
        "description": "Task records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "subject": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Task subject"},
            "project_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "projects", "fk_lookup_fields": ["id", "name"], "description": "Project"},
            "parent_task_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "tasks", "fk_lookup_fields": ["id", "subject"], "description": "Parent task"},
            "assigned_to_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Assigned to"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "working", "pending_review", "overdue", "completed", "cancelled"], "default": "open", "description": "Status"},
            "priority": {"type": FieldType.ENUM, "enum_values": ["low", "medium", "high", "urgent"], "default": "medium", "description": "Priority"},
            "is_group": {"type": FieldType.BOOLEAN, "default": False, "description": "Is parent/group task"},
            "is_milestone": {"type": FieldType.BOOLEAN, "default": False, "description": "Is milestone"},
            "exp_start": {"type": FieldType.DATE, "description": "Expected start date"},
            "exp_end": {"type": FieldType.DATE, "description": "Expected end date"},
            "actual_start": {"type": FieldType.DATE, "description": "Actual start date"},
            "actual_end": {"type": FieldType.DATE, "description": "Actual end date"},
            "expected_time": {"type": FieldType.DECIMAL, "description": "Expected time (hours)"},
            "actual_time": {"type": FieldType.DECIMAL, "description": "Actual time (hours)"},
            "progress": {"type": FieldType.DECIMAL, "default": 0, "description": "Progress percentage"},
            "description": {"type": FieldType.STRING, "description": "Task description"},
            "depends_on": {"type": FieldType.STRING, "description": "Dependencies (task IDs)"},
        },
        "required_fields": ["subject"],
        "unique_fields": [],
        "lookup_fields": ["id", "subject"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
