"""Purchasing entity definitions: suppliers, purchase invoices, supplier payments."""
from .base import FieldType, EntityConfig

PURCHASING_ENTITIES: dict[str, EntityConfig] = {
    "suppliers": {
        "model_name": "Supplier",
        "display_name": "Suppliers",
        "description": "Vendor/supplier records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "normalizer": "name", "description": "Supplier name"},
            "email": {"type": FieldType.EMAIL, "normalizer": "email", "description": "Email address"},
            "phone": {"type": FieldType.PHONE, "normalizer": "phone", "description": "Phone number"},
            "address": {"type": FieldType.STRING, "normalizer": "address", "description": "Address"},
            "city": {"type": FieldType.STRING, "max_length": 100, "description": "City"},
            "state": {"type": FieldType.STRING, "max_length": 100, "description": "State"},
            "country": {"type": FieldType.STRING, "max_length": 100, "default": "Nigeria", "description": "Country"},
            "tax_id": {"type": FieldType.STRING, "max_length": 50, "description": "Tax ID"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Default currency"},
            "payment_terms": {"type": FieldType.INTEGER, "description": "Payment terms (days)"},
        },
        "required_fields": ["name"],
        "unique_fields": ["email", "tax_id"],
        "lookup_fields": ["id", "email", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "purchase_invoices": {
        "model_name": "PurchaseInvoice",
        "display_name": "Purchase Invoices (Bills)",
        "description": "Bills from suppliers",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "bill_number": {"type": FieldType.STRING, "unique": True, "max_length": 50, "description": "Bill number"},
            "supplier_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "suppliers", "fk_lookup_fields": ["id", "email", "name"], "description": "Supplier"},
            "bill_date": {"type": FieldType.DATE, "required": True, "description": "Bill date"},
            "due_date": {"type": FieldType.DATE, "description": "Due date"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Subtotal"},
            "tax_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Tax amount"},
            "total_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "pending", "paid", "partially_paid", "overdue", "cancelled"], "default": "pending", "description": "Status"},
        },
        "required_fields": ["supplier_id", "bill_date", "amount"],
        "unique_fields": ["bill_number"],
        "lookup_fields": ["id", "bill_number"],
        "dependencies": ["suppliers"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "supplier_payments": {
        "model_name": "SupplierPayment",
        "display_name": "Supplier Payments",
        "description": "Payments made to suppliers/vendors",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "payment_number": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 100, "description": "Payment number"},
            "supplier_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "suppliers", "fk_lookup_fields": ["id", "email", "name"], "description": "Supplier"},
            "payment_date": {"type": FieldType.DATE, "required": True, "description": "Payment date"},
            "posting_date": {"type": FieldType.DATE, "required": True, "description": "Posting date"},
            "mode_of_payment": {"type": FieldType.STRING, "max_length": 100, "description": "Payment mode"},
            "bank_account_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "bank_accounts", "fk_lookup_fields": ["id", "account_name"], "description": "Bank account"},
            "currency": {"type": FieldType.STRING, "max_length": 10, "default": "NGN", "description": "Currency"},
            "paid_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Amount paid"},
            "reference_number": {"type": FieldType.STRING, "max_length": 255, "description": "Reference number"},
            "remarks": {"type": FieldType.STRING, "description": "Remarks"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "submitted", "approved", "posted", "cancelled"], "default": "draft", "description": "Status"},
        },
        "required_fields": ["payment_number", "payment_date", "posting_date", "paid_amount"],
        "unique_fields": ["payment_number"],
        "lookup_fields": ["id", "payment_number", "reference_number"],
        "dependencies": ["suppliers", "bank_accounts"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
