"""Sales entity definitions: invoices, payments, credit notes."""
from .base import FieldType, EntityConfig

SALES_ENTITIES: dict[str, EntityConfig] = {
    "invoices": {
        "model_name": "Invoice",
        "display_name": "Invoices",
        "description": "Sales invoices",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "invoice_number": {"type": FieldType.STRING, "unique": True, "max_length": 50, "description": "Invoice number"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "invoice_date": {"type": FieldType.DATE, "required": True, "description": "Invoice date"},
            "due_date": {"type": FieldType.DATE, "description": "Due date"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Subtotal amount"},
            "tax_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Tax amount"},
            "total_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total amount (calculated)"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency code"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "pending", "paid", "partially_paid", "overdue", "cancelled", "refunded"], "default": "pending", "description": "Invoice status"},
            "description": {"type": FieldType.STRING, "description": "Invoice description/memo"},
        },
        "required_fields": ["customer_id", "invoice_date", "amount"],
        "unique_fields": ["invoice_number"],
        "lookup_fields": ["id", "invoice_number"],
        "dependencies": ["customers"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "payments": {
        "model_name": "Payment",
        "display_name": "Payments",
        "description": "Customer payments",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "receipt_number": {"type": FieldType.STRING, "unique": True, "max_length": 50, "description": "Receipt number"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "invoice_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "invoices", "fk_lookup_fields": ["id", "invoice_number"], "description": "Invoice (optional)"},
            "payment_date": {"type": FieldType.DATE, "required": True, "description": "Payment date"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Payment amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency code"},
            "payment_method": {"type": FieldType.ENUM, "enum_values": ["cash", "bank_transfer", "card", "mobile_money", "paystack", "flutterwave", "other"], "description": "Payment method"},
            "status": {"type": FieldType.ENUM, "enum_values": ["pending", "approved", "posted", "completed", "failed", "refunded"], "default": "completed", "description": "Payment status"},
            "transaction_reference": {"type": FieldType.STRING, "max_length": 100, "description": "Transaction reference"},
            "notes": {"type": FieldType.STRING, "description": "Payment notes"},
        },
        "required_fields": ["customer_id", "payment_date", "amount"],
        "unique_fields": ["receipt_number"],
        "lookup_fields": ["id", "receipt_number", "transaction_reference"],
        "dependencies": ["customers"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "credit_notes": {
        "model_name": "CreditNote",
        "display_name": "Credit Notes",
        "description": "Customer credit notes/adjustments",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "credit_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Credit note number"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "invoice_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "invoices", "fk_lookup_fields": ["id", "invoice_number"], "description": "Related invoice"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Subtotal amount"},
            "tax_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "default": 0, "description": "Tax amount"},
            "total_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total amount"},
            "currency": {"type": FieldType.STRING, "max_length": 10, "default": "NGN", "description": "Currency"},
            "status": {"type": FieldType.ENUM, "enum_values": ["draft", "issued", "applied", "cancelled"], "default": "draft", "description": "Status"},
            "issue_date": {"type": FieldType.DATETIME, "description": "Issue date"},
            "posting_date": {"type": FieldType.DATETIME, "description": "Posting date"},
        },
        "required_fields": ["amount"],
        "unique_fields": ["credit_number"],
        "lookup_fields": ["id", "credit_number"],
        "dependencies": ["customers", "invoices"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
