"""Support entity definitions: tickets, agents, automation."""
from .base import FieldType, EntityConfig

SUPPORT_ENTITIES: dict[str, EntityConfig] = {
    "tickets": {
        "model_name": "Ticket",
        "display_name": "Support Tickets",
        "description": "Help desk tickets",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "ticket_number": {"type": FieldType.STRING, "unique": True, "max_length": 50, "description": "Ticket number"},
            "subject": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Subject"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "customer_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "customers", "fk_lookup_fields": ["id", "email", "name"], "description": "Customer"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "assigned_employee_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Assigned to"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "replied", "resolved", "closed", "on_hold"], "default": "open", "description": "Status"},
            "priority": {"type": FieldType.ENUM, "enum_values": ["low", "medium", "high", "urgent"], "default": "medium", "description": "Priority"},
            "ticket_type": {"type": FieldType.STRING, "max_length": 100, "description": "Ticket type"},
            "channel": {"type": FieldType.ENUM, "enum_values": ["email", "phone", "chat", "web", "social", "other"], "default": "email", "description": "Channel"},
            "first_response_time": {"type": FieldType.DATETIME, "description": "First response time"},
            "resolution_time": {"type": FieldType.DATETIME, "description": "Resolution time"},
        },
        "required_fields": ["subject"],
        "unique_fields": ["ticket_number"],
        "lookup_fields": ["id", "ticket_number"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "unified_tickets": {
        "model_name": "UnifiedTicket",
        "display_name": "Unified Tickets",
        "description": "Unified ticket system with multi-channel support",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "ticket_number": {"type": FieldType.STRING, "unique": True, "max_length": 100, "description": "Ticket number"},
            "subject": {"type": FieldType.STRING, "required": True, "max_length": 500, "description": "Subject"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "contact_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "contacts", "fk_lookup_fields": ["id", "email", "name"], "description": "Contact"},
            "agent_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "agents", "fk_lookup_fields": ["id", "email"], "description": "Assigned agent"},
            "status": {"type": FieldType.ENUM, "enum_values": ["new", "open", "pending", "resolved", "closed"], "default": "new", "description": "Status"},
            "priority": {"type": FieldType.ENUM, "enum_values": ["low", "normal", "high", "urgent"], "default": "normal", "description": "Priority"},
            "channel": {"type": FieldType.ENUM, "enum_values": ["email", "phone", "chat", "whatsapp", "facebook", "twitter", "instagram", "web", "api"], "default": "email", "description": "Channel"},
            "category": {"type": FieldType.STRING, "max_length": 255, "description": "Category"},
            "tags": {"type": FieldType.JSON, "description": "Tags array"},
            "sla_due_date": {"type": FieldType.DATETIME, "description": "SLA due date"},
            "first_response_at": {"type": FieldType.DATETIME, "description": "First response timestamp"},
            "resolved_at": {"type": FieldType.DATETIME, "description": "Resolution timestamp"},
            "closed_at": {"type": FieldType.DATETIME, "description": "Closed timestamp"},
        },
        "required_fields": ["subject"],
        "unique_fields": ["ticket_number"],
        "lookup_fields": ["id", "ticket_number"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "ticket_comments": {
        "model_name": "TicketComment",
        "display_name": "Ticket Comments",
        "description": "Ticket comments and communications",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "ticket_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "tickets", "fk_lookup_fields": ["id", "ticket_number"], "description": "Ticket"},
            "comment_type": {"type": FieldType.ENUM, "enum_values": ["reply", "note", "system"], "default": "reply", "description": "Comment type"},
            "content": {"type": FieldType.STRING, "required": True, "description": "Comment content"},
            "is_public": {"type": FieldType.BOOLEAN, "default": True, "description": "Is visible to customer"},
            "author_type": {"type": FieldType.ENUM, "enum_values": ["customer", "agent", "system"], "default": "agent", "description": "Author type"},
            "author_id": {"type": FieldType.INTEGER, "description": "Author ID"},
            "author_name": {"type": FieldType.STRING, "max_length": 255, "description": "Author name"},
        },
        "required_fields": ["ticket_id", "content"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["tickets"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "ticket_communications": {
        "model_name": "TicketCommunication",
        "display_name": "Ticket Communications",
        "description": "Email/chat communications on tickets",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "unified_ticket_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "unified_tickets", "fk_lookup_fields": ["id", "ticket_number"], "description": "Unified ticket"},
            "direction": {"type": FieldType.ENUM, "required": True, "enum_values": ["inbound", "outbound"], "description": "Direction"},
            "channel": {"type": FieldType.ENUM, "enum_values": ["email", "phone", "chat", "whatsapp", "sms"], "default": "email", "description": "Channel"},
            "subject": {"type": FieldType.STRING, "max_length": 500, "description": "Subject"},
            "content": {"type": FieldType.STRING, "required": True, "description": "Content"},
            "sender": {"type": FieldType.STRING, "max_length": 255, "description": "Sender"},
            "recipients": {"type": FieldType.JSON, "description": "Recipients array"},
            "message_id": {"type": FieldType.STRING, "max_length": 255, "description": "External message ID"},
        },
        "required_fields": ["unified_ticket_id", "direction", "content"],
        "unique_fields": [],
        "lookup_fields": ["id", "message_id"],
        "dependencies": ["unified_tickets"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "agents": {
        "model_name": "Agent",
        "display_name": "Support Agents",
        "description": "Support/helpdesk agents",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "normalizer": "name", "description": "Agent name"},
            "email": {"type": FieldType.EMAIL, "required": True, "unique": True, "normalizer": "email", "description": "Email"},
            "employee_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "employees", "fk_lookup_fields": ["id", "email"], "description": "Linked employee"},
            "role": {"type": FieldType.ENUM, "enum_values": ["agent", "supervisor", "admin"], "default": "agent", "description": "Agent role"},
            "status": {"type": FieldType.ENUM, "enum_values": ["active", "inactive", "away"], "default": "active", "description": "Status"},
            "max_tickets": {"type": FieldType.INTEGER, "default": 10, "description": "Max concurrent tickets"},
            "skills": {"type": FieldType.JSON, "description": "Skills/categories array"},
        },
        "required_fields": ["name", "email"],
        "unique_fields": ["email"],
        "lookup_fields": ["id", "email", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "canned_responses": {
        "model_name": "CannedResponse",
        "display_name": "Canned Responses",
        "description": "Pre-written response templates",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "title": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Response title"},
            "content": {"type": FieldType.STRING, "required": True, "description": "Response content"},
            "category": {"type": FieldType.STRING, "max_length": 100, "description": "Category"},
            "shortcut": {"type": FieldType.STRING, "max_length": 50, "description": "Keyboard shortcut"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
        },
        "required_fields": ["title", "content"],
        "unique_fields": ["title"],
        "lookup_fields": ["id", "title"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "automation_rules": {
        "model_name": "AutomationRule",
        "display_name": "Automation Rules",
        "description": "Ticket automation rules",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Rule name"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "trigger_event": {"type": FieldType.ENUM, "required": True, "enum_values": ["ticket_created", "ticket_updated", "ticket_assigned", "sla_breach", "time_based"], "description": "Trigger event"},
            "conditions": {"type": FieldType.JSON, "description": "Conditions JSON"},
            "actions": {"type": FieldType.JSON, "description": "Actions JSON"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
            "priority": {"type": FieldType.INTEGER, "default": 0, "description": "Execution priority"},
        },
        "required_fields": ["name", "trigger_event"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "automation_logs": {
        "model_name": "AutomationLog",
        "display_name": "Automation Logs",
        "description": "Automation execution logs",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "rule_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "automation_rules", "fk_lookup_fields": ["id", "name"], "description": "Automation rule"},
            "ticket_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "tickets", "fk_lookup_fields": ["id", "ticket_number"], "description": "Ticket"},
            "unified_ticket_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "unified_tickets", "fk_lookup_fields": ["id", "ticket_number"], "description": "Unified ticket"},
            "executed_at": {"type": FieldType.DATETIME, "required": True, "description": "Execution timestamp"},
            "status": {"type": FieldType.ENUM, "enum_values": ["success", "failure", "skipped"], "default": "success", "description": "Execution status"},
            "actions_taken": {"type": FieldType.JSON, "description": "Actions taken JSON"},
            "error_message": {"type": FieldType.STRING, "description": "Error message if failed"},
        },
        "required_fields": ["rule_id", "executed_at"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["automation_rules"],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
