"""Tax entity definitions: tax codes, rates, transactions."""
from .base import FieldType, EntityConfig

TAX_ENTITIES: dict[str, EntityConfig] = {
    # =========================================================================
    # TAX MASTERS (6 entities)
    # =========================================================================
    "tax_codes": {
        "model_name": "TaxCode",
        "display_name": "Tax Codes",
        "description": "Tax rate definitions",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "code": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 50, "description": "Tax code"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Tax name"},
            "tax_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["vat", "wht", "stamp_duty", "paye", "cit", "other"], "description": "Tax type"},
            "rate": {"type": FieldType.DECIMAL, "required": True, "description": "Tax rate percentage"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "is_active": {"type": FieldType.BOOLEAN, "default": True, "description": "Is active"},
            "effective_from": {"type": FieldType.DATE, "description": "Effective from date"},
            "effective_to": {"type": FieldType.DATE, "description": "Effective to date"},
        },
        "required_fields": ["code", "name", "tax_type", "rate"],
        "unique_fields": ["code"],
        "lookup_fields": ["id", "code", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_categories": {
        "model_name": "TaxCategory",
        "display_name": "Tax Categories",
        "description": "Tax category master",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Category name"},
            "tax_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["vat", "wht", "stamp_duty", "paye", "cit", "other"], "description": "Tax type"},
            "description": {"type": FieldType.STRING, "description": "Description"},
            "is_default": {"type": FieldType.BOOLEAN, "default": False, "description": "Is default category"},
        },
        "required_fields": ["name", "tax_type"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_rates": {
        "model_name": "TaxRate",
        "display_name": "Tax Rates",
        "description": "Tax rate history with effective dates",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "tax_category_id": {"type": FieldType.FOREIGN_KEY, "required": True, "fk_entity": "tax_categories", "fk_lookup_fields": ["id", "name"], "description": "Tax category"},
            "rate": {"type": FieldType.DECIMAL, "required": True, "description": "Tax rate percentage"},
            "effective_from": {"type": FieldType.DATE, "required": True, "description": "Effective from date"},
            "effective_to": {"type": FieldType.DATE, "description": "Effective to date"},
            "description": {"type": FieldType.STRING, "description": "Description"},
        },
        "required_fields": ["tax_category_id", "rate", "effective_from"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": ["tax_categories"],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_withholding_categories": {
        "model_name": "TaxWithholdingCategory",
        "display_name": "WHT Categories",
        "description": "Withholding tax categories",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "unique": True, "max_length": 255, "description": "Category name"},
            "category_name": {"type": FieldType.STRING, "max_length": 255, "description": "Display name"},
            "rate": {"type": FieldType.DECIMAL, "required": True, "description": "WHT rate percentage"},
            "threshold_amount": {"type": FieldType.DECIMAL, "description": "Threshold amount for WHT"},
            "round_off_tax_amount": {"type": FieldType.BOOLEAN, "default": False, "description": "Round off tax amount"},
            "consider_party_ledger_amount": {"type": FieldType.BOOLEAN, "default": False, "description": "Consider party ledger amount"},
        },
        "required_fields": ["name", "rate"],
        "unique_fields": ["name"],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_rules": {
        "model_name": "TaxRule",
        "display_name": "Tax Rules",
        "description": "Dynamic tax rule matching",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Rule name"},
            "tax_type": {"type": FieldType.STRING, "max_length": 100, "description": "Tax type"},
            "use_for_shopping_cart": {"type": FieldType.BOOLEAN, "default": False, "description": "Use for shopping cart"},
            "billing_city": {"type": FieldType.STRING, "max_length": 255, "description": "Billing city"},
            "billing_state": {"type": FieldType.STRING, "max_length": 255, "description": "Billing state"},
            "billing_country": {"type": FieldType.STRING, "max_length": 255, "description": "Billing country"},
            "shipping_city": {"type": FieldType.STRING, "max_length": 255, "description": "Shipping city"},
            "shipping_state": {"type": FieldType.STRING, "max_length": 255, "description": "Shipping state"},
            "shipping_country": {"type": FieldType.STRING, "max_length": 255, "description": "Shipping country"},
            "from_date": {"type": FieldType.DATE, "description": "Effective from date"},
            "to_date": {"type": FieldType.DATE, "description": "Effective to date"},
            "priority": {"type": FieldType.INTEGER, "description": "Rule priority"},
        },
        "required_fields": ["name"],
        "unique_fields": [],
        "lookup_fields": ["id", "name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_regions": {
        "model_name": "TaxRegion",
        "display_name": "Tax Regions",
        "description": "Country/region tax configuration",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "country": {"type": FieldType.STRING, "required": True, "max_length": 100, "description": "Country code"},
            "state": {"type": FieldType.STRING, "max_length": 100, "description": "State/region"},
            "vat_rate": {"type": FieldType.DECIMAL, "description": "Default VAT rate"},
            "wht_rate": {"type": FieldType.DECIMAL, "description": "Default WHT rate"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "description": "Currency"},
            "fiscal_year_start": {"type": FieldType.STRING, "max_length": 10, "description": "Fiscal year start (MM-DD)"},
        },
        "required_fields": ["country"],
        "unique_fields": [],
        "lookup_fields": ["id", "country"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    # =========================================================================
    # TAX TRANSACTIONS (4 entities)
    # =========================================================================
    "tax_transactions": {
        "model_name": "TaxTransaction",
        "display_name": "Tax Transactions",
        "description": "Generic tax ledger",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "transaction_date": {"type": FieldType.DATE, "required": True, "description": "Transaction date"},
            "tax_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["vat", "wht", "stamp_duty", "paye", "cit", "other"], "description": "Tax type"},
            "tax_code_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "tax_codes", "fk_lookup_fields": ["id", "code"], "description": "Tax code"},
            "base_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Base amount"},
            "tax_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Tax amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "party_type": {"type": FieldType.ENUM, "enum_values": ["customer", "supplier", "employee"], "description": "Party type"},
            "party_name": {"type": FieldType.STRING, "max_length": 255, "description": "Party name"},
            "reference_doctype": {"type": FieldType.STRING, "max_length": 100, "description": "Reference document type"},
            "reference_name": {"type": FieldType.STRING, "max_length": 255, "description": "Reference document ID"},
            "is_return": {"type": FieldType.BOOLEAN, "default": False, "description": "Is return/refund"},
        },
        "required_fields": ["transaction_date", "tax_type", "base_amount", "tax_amount"],
        "unique_fields": [],
        "lookup_fields": ["id"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_filing_periods": {
        "model_name": "TaxFilingPeriod",
        "display_name": "Tax Filing Periods",
        "description": "Filing period tracking",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "tax_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["vat", "wht", "stamp_duty", "paye", "cit", "other"], "description": "Tax type"},
            "period_name": {"type": FieldType.STRING, "required": True, "max_length": 100, "description": "Period name (e.g., 2024-Q1)"},
            "start_date": {"type": FieldType.DATE, "required": True, "description": "Period start date"},
            "end_date": {"type": FieldType.DATE, "required": True, "description": "Period end date"},
            "due_date": {"type": FieldType.DATE, "description": "Filing due date"},
            "status": {"type": FieldType.ENUM, "enum_values": ["open", "filed", "paid", "overdue"], "default": "open", "description": "Filing status"},
            "amount_due": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Amount due"},
            "amount_paid": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Amount paid"},
            "filing_reference": {"type": FieldType.STRING, "max_length": 255, "description": "Filing reference number"},
        },
        "required_fields": ["tax_type", "period_name", "start_date", "end_date"],
        "unique_fields": [],
        "lookup_fields": ["id", "period_name"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "tax_payments": {
        "model_name": "TaxPayment",
        "display_name": "Tax Payments",
        "description": "Tax payment records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "payment_date": {"type": FieldType.DATE, "required": True, "description": "Payment date"},
            "tax_type": {"type": FieldType.ENUM, "required": True, "enum_values": ["vat", "wht", "stamp_duty", "paye", "cit", "other"], "description": "Tax type"},
            "filing_period_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "tax_filing_periods", "fk_lookup_fields": ["id", "period_name"], "description": "Filing period"},
            "amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Payment amount"},
            "currency": {"type": FieldType.STRING, "max_length": 3, "default": "NGN", "description": "Currency"},
            "payment_reference": {"type": FieldType.STRING, "max_length": 255, "description": "Payment reference"},
            "bank_account_id": {"type": FieldType.FOREIGN_KEY, "fk_entity": "bank_accounts", "fk_lookup_fields": ["id", "account_name"], "description": "Bank account"},
            "remarks": {"type": FieldType.STRING, "description": "Remarks"},
        },
        "required_fields": ["payment_date", "tax_type", "amount"],
        "unique_fields": [],
        "lookup_fields": ["id", "payment_reference"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "company_tax_settings": {
        "model_name": "CompanyTaxSettings",
        "display_name": "Company Tax Settings",
        "description": "Per-company tax configuration",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "company": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Company name"},
            "tax_id": {"type": FieldType.STRING, "max_length": 100, "description": "Tax ID (TIN)"},
            "vat_registration_number": {"type": FieldType.STRING, "max_length": 100, "description": "VAT registration number"},
            "default_vat_rate": {"type": FieldType.DECIMAL, "description": "Default VAT rate"},
            "default_wht_rate": {"type": FieldType.DECIMAL, "description": "Default WHT rate"},
            "tax_filing_frequency": {"type": FieldType.ENUM, "enum_values": ["monthly", "quarterly", "annually"], "default": "monthly", "description": "Filing frequency"},
            "vat_account": {"type": FieldType.STRING, "max_length": 255, "description": "VAT liability account"},
            "wht_account": {"type": FieldType.STRING, "max_length": 255, "description": "WHT account"},
        },
        "required_fields": ["company"],
        "unique_fields": ["company"],
        "lookup_fields": ["id", "company"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    # =========================================================================
    # NIGERIAN TAX (2 entities)
    # =========================================================================
    "ng_vat_transactions": {
        "model_name": "NGVATTransaction",
        "display_name": "Nigeria VAT Transactions",
        "description": "Nigeria VAT ledger entries",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "transaction_date": {"type": FieldType.DATE, "required": True, "description": "Transaction date"},
            "invoice_number": {"type": FieldType.STRING, "max_length": 100, "description": "Invoice number"},
            "customer_name": {"type": FieldType.STRING, "max_length": 255, "description": "Customer name"},
            "customer_tin": {"type": FieldType.STRING, "max_length": 50, "description": "Customer TIN"},
            "supply_type": {"type": FieldType.ENUM, "enum_values": ["goods", "services", "both"], "default": "goods", "description": "Supply type"},
            "taxable_value": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Taxable value"},
            "vat_rate": {"type": FieldType.DECIMAL, "default": 7.5, "description": "VAT rate"},
            "vat_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "VAT amount"},
            "total_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Total amount"},
            "is_exempt": {"type": FieldType.BOOLEAN, "default": False, "description": "Is VAT exempt"},
            "exemption_reason": {"type": FieldType.STRING, "description": "Exemption reason"},
        },
        "required_fields": ["transaction_date", "taxable_value", "vat_amount"],
        "unique_fields": [],
        "lookup_fields": ["id", "invoice_number"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },

    "ng_wht_transactions": {
        "model_name": "NGWHTTransaction",
        "display_name": "Nigeria WHT Transactions",
        "description": "Nigeria withholding tax records",
        "fields": {
            "id": {"type": FieldType.INTEGER, "description": "Internal ID"},
            "transaction_date": {"type": FieldType.DATE, "required": True, "description": "Transaction date"},
            "vendor_name": {"type": FieldType.STRING, "required": True, "max_length": 255, "description": "Vendor name"},
            "vendor_tin": {"type": FieldType.STRING, "max_length": 50, "description": "Vendor TIN"},
            "wht_category": {"type": FieldType.STRING, "max_length": 100, "description": "WHT category"},
            "invoice_number": {"type": FieldType.STRING, "max_length": 100, "description": "Invoice number"},
            "gross_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "Gross amount"},
            "wht_rate": {"type": FieldType.DECIMAL, "required": True, "description": "WHT rate"},
            "wht_amount": {"type": FieldType.DECIMAL, "required": True, "normalizer": "currency", "description": "WHT amount"},
            "net_amount": {"type": FieldType.DECIMAL, "normalizer": "currency", "description": "Net amount after WHT"},
            "certificate_number": {"type": FieldType.STRING, "max_length": 100, "description": "WHT certificate number"},
            "is_remitted": {"type": FieldType.BOOLEAN, "default": False, "description": "Is remitted to FIRS"},
            "remittance_date": {"type": FieldType.DATE, "description": "Remittance date"},
        },
        "required_fields": ["transaction_date", "vendor_name", "gross_amount", "wht_rate", "wht_amount"],
        "unique_fields": [],
        "lookup_fields": ["id", "certificate_number"],
        "dependencies": [],
        "supports_upsert": True,
        "supports_rollback": True,
    },
}
